eureka:
  client:
    serviceUrl:
      defaultZone: '{cipher}AQA/NB/V/XGGgN5R7ArjPcgTd5E9s+8vTTXmgDM19T1z/vySVUAZ1VThdBIOJlsfOASmBd78cvJ9K+FoPIHL9r511b3BZQXbp6Q5fZZwOEriqhNzOpyPXL3dVtM3Ou6RbmtkeeXh1tL2bQhU++1p7DIPPwEUB+UpM7RGkU4aTfcO5GkGhbM/UtasOk7oS67hYXjNENQP6K262Wf3jdg1+p7madAuXru/TtOsMqoV6j0DitkD6HKXxZ7cqFwYeZgN3dQLDOUUpa/+8M8LtFTeouXVB5EwVIo6fAPXYJxRIB9RCUDxh8A0fhhSfJ23l21eZbPkw9+TK22z7COshhi0sej+23dkajFHP6++gL6RR31l3cmvjCCyt8BXaIu7JJs9p0py6RLWgWUv5fMOFK5+S5uPQ9Jt7ZHB7cFCVINp3t8G4w=='
spring:
  cloud:
    stream:
      bindings:
        gdin:
          destination: 5010,5011,5030,5050,5060,5110,5120,5140,5040,5160,5180,5190,5210,5220,5240,5250,5020,5260,5270,dmap_media_resend
          binder: kafkagd
          group: test
          contentType: text/plain
          consumer:
            headerMode: raw
            concurrency: 2
        yzin:
          destination: 5010,5011,5030,5050,5060,5110,5120,5140,5040,5160,5180,5190,5210,5220,5240,5250,5020,5260,5270,dmap_media_resend
          binder: kafkayz
          group: test
          contentType: text/plain
          consumer:
            headerMode: raw
            concurrency: 2            
      binders:
        kafkagd:
          type: kafka
          defaultCandidate: false
          environment:
            spring:
              cloud:
                stream: 
                  kafka:
                    binder:
                      brokers: '{cipher}AQAEct4Z2gPk2i0Jvgi6kluJivEPnW2SGLRIa5FsJpPdnwplaijZChpJZTFL/1V/c8850zztaN2JwoJysGLDSxJHwoWGapHJLXaj2Yg+6T9xMf+HbyY11mVtaRge5GD+f29WbkVzuvzT1TUe5qLE3qpk8AWUQpB7LeWiBBEOEJ0e69jhc4LPpEtsryY4YIPgLV8QCyIZGh8f6q9RujrpfcHZ2ibBsfB9WuSXS9Z9ebGDCsi7fXfS8qhy67pq/k+l3cANVsDIF/j5Gukjmi43ix0WQEhU8zmQavi8zHWN0dB94fHqzIlcZC6of5s2P+BiiV6sfsT0+fRTJ7IhY9Jtc3diOVNJhlqk3e/PGZ2BTs+gh6nqGEbzX6NUoBZbt/9fjCXAsU31s4Qyeo+tLj4KBLEAbJr2+vfsdaX10tvSF19+M03pvjkRucj2mcSOdVhm/HI='
                      zkNodes: 121.201.104.50,121.201.104.52,121.201.104.53
                      requiredAcks: 1
                      autoCreateTopics: false
                    bindings:
                      gdin:
                        consumer:
                          autoRebalanceEnabled: true
                          autoCommitOffset: false
                          autoCommitOnError: false
                          startOffset: latest
                          enableDlq: true
                          dlqName: dmap_media_resend
        kafkayz:
          type: kafka
          environment:
            spring:
              cloud:
                stream: 
                  kafka:
                    binder:
                      brokers: '{cipher}AQA+00cs6IJl8m2t2LsBYX+HWYFTiuQGW0p7Plyq6fEmvdsEBCiCx8gqGzknFQGffJN3AEL8aupgfMlgshfseUBwWtJArL/gNl9r1gfqWHe0n+sWCyI7+3+3wrogZJ01HfgRjRtxQBMCUhlGlbvytyJw3t1Sn2uAaSUOyu4MmqPsqnN+j4eYVYQYCKsqlKAk7aILafZW/GhJV3nlqlOuKh9u0VuvmHgSF6B+edzW3cZwXUl7L0ibWB/wRY+gjWz+++8M3iXOq2/nwpmStrBjtiEGKcuFYdfxvQ4h88dXIuG7eUcvnWlvBpfMg1WFIJ7HVSP8Q6Z7mU9qaU7XJ6/41wBuM160U4Gtd+L/ZftQa0VRVAy7tMKeTR4IWOMZXLhnHNRwi95tjoRJaniMntR312Hwi28m7fzzhAd4FoBsTrrwSbO5+AhIt/Ib+7Lvtlb3EPQ='
                      zkNodes: 123.59.17.83,123.59.17.180,123.59.17.181
                      requiredAcks: 1
                      autoCreateTopics: false
                    bindings:
                      yzin:
                        consumer:
                          autoRebalanceEnabled: true
                          autoCommitOffset: false
                          autoCommitOnError: false
                          startOffset: latest
                          enableDlq: true
                          dlqName: dmap_media_resend                           
---
#亦庄Consumer发往亦庄Redis的第一组程序          
spring:
  profiles: ytyg1prd
server:
  port: ${port:19930}
