eureka:
  client:
    serviceUrl:
      defaultZone: '{cipher}AQAZqayNZZBQGm+6XSlpRn85ESQxVxKokpoi43nvgns8ICrAWCOX4qE1uy38rCLt4JGxTmLmoBQ062HZIWSYlL8wyw7MdWHjDNvftJusByZuWk9KbSVcCVHwO9/DPJJYKUz55NhVp4lMof6xQIvgThSf/H+AcCRVH5Mb9L6vky9i9soUPkyx3BOpH9JWHs4E2Oj9lQK5dQ1pHqOJ0TxqT122sURCDaL9kaSaTtPY7MpbKLGuDjsRXETCu3OO6s0bVBDx6AF9GVRuDD5MGTw/Q9G7QUQyh9GX0yRI5FAco+40V50tlw9Rc70bUh+6t0Pq4Tg+kknrvi7Wa97aw1a0BDMz91MowmYQs7NybKq3yLsZCvjJKf65fskMG0jGkIblojkvI4J1AU2r8kjIqKhX9kGIs/Xej+FfeUzHhq6rGaT1Uw=='
spring:
  cloud:
    stream:            
      binders:
        kafkagd:
          type: kafka
          inheritEnvironment: false
          defaultCandidate: false
          environment:
            spring:
              cloud:
                stream: 
                  kafka:
                    binder:
                      brokers: '{cipher}AQAEct4Z2gPk2i0Jvgi6kluJivEPnW2SGLRIa5FsJpPdnwplaijZChpJZTFL/1V/c8850zztaN2JwoJysGLDSxJHwoWGapHJLXaj2Yg+6T9xMf+HbyY11mVtaRge5GD+f29WbkVzuvzT1TUe5qLE3qpk8AWUQpB7LeWiBBEOEJ0e69jhc4LPpEtsryY4YIPgLV8QCyIZGh8f6q9RujrpfcHZ2ibBsfB9WuSXS9Z9ebGDCsi7fXfS8qhy67pq/k+l3cANVsDIF/j5Gukjmi43ix0WQEhU8zmQavi8zHWN0dB94fHqzIlcZC6of5s2P+BiiV6sfsT0+fRTJ7IhY9Jtc3diOVNJhlqk3e/PGZ2BTs+gh6nqGEbzX6NUoBZbt/9fjCXAsU31s4Qyeo+tLj4KBLEAbJr2+vfsdaX10tvSF19+M03pvjkRucj2mcSOdVhm/HI='
                      zkNodes: '{cipher}AQACy18dJA1HRIomSjcDx18ClYtA9fUCBXrum7FSBhPR3P16hqu+lfBZYAheOIuzdlumUSKE/LGWgnmpPb6wrHKCmZ0VtQyplPO7FLF9S5fde/mC+jMBWBE/8+a7gWHiG/bYvTu9MYnJF2xlLDi+fTGNuJdwvTmV0KRmS7Dgl0J7UmI5nj07RnMAlxp6ZerKzX/LY40YeWrcR0cjpi0j0+IgRDymuzf4B9VygsLWYNA8ZLkxLaEbqzjZu/KjrzpvBsZaEAXG7qJ6eALZUX2S81kY3cEij/EbJVlmwPi7fMvdJjCJBmc50SDK9c3l7Gjq7oHB6R6+7BgKDYtLijzooYX1eVoX7b9memJdg5tfYMPTbVO8V/rgobTeuu/uSTrKD0NK9ss6wy5YhU6l0GsvB3QWrmhxmTc00dirmV4h3SStNQ=='
                      autoCreateTopics: false
                    bindings:
                      gdin:
                        consumer:
                          autoCommitOnError: true
                          startOffset: latest
                          enableDlq: true
                          dlqName: dmap_media_resend
                          configuration:
                            session.timeout.ms: 120000                          
        kafkayz:
          type: kafka
          inheritEnvironment: false
          defaultCandidate: false
          environment:
            spring:
              cloud:
                stream: 
                  kafka:
                    binder:
                      brokers: '{cipher}AQA+00cs6IJl8m2t2LsBYX+HWYFTiuQGW0p7Plyq6fEmvdsEBCiCx8gqGzknFQGffJN3AEL8aupgfMlgshfseUBwWtJArL/gNl9r1gfqWHe0n+sWCyI7+3+3wrogZJ01HfgRjRtxQBMCUhlGlbvytyJw3t1Sn2uAaSUOyu4MmqPsqnN+j4eYVYQYCKsqlKAk7aILafZW/GhJV3nlqlOuKh9u0VuvmHgSF6B+edzW3cZwXUl7L0ibWB/wRY+gjWz+++8M3iXOq2/nwpmStrBjtiEGKcuFYdfxvQ4h88dXIuG7eUcvnWlvBpfMg1WFIJ7HVSP8Q6Z7mU9qaU7XJ6/41wBuM160U4Gtd+L/ZftQa0VRVAy7tMKeTR4IWOMZXLhnHNRwi95tjoRJaniMntR312Hwi28m7fzzhAd4FoBsTrrwSbO5+AhIt/Ib+7Lvtlb3EPQ='
                      zkNodes: '{cipher}AQAM92XGYxBzvvPhVmloB2Xa+RYu1Z6bDIptj5dNZpgD1e5BP7I8EQS/UC0QXL93Jzy/6IyEaiOiQxruGgEOgctQHqDu9HOZLbNvJs8QTHIR5uUKirIE2RxT0pKPWszdu6ru39K4/RzpPTiBApWxQKAMRNqfh2xU6ofaqEQYN79jMYVr2usq08iaa3jmnahYrMmACGSN7tgOFEnrgAY/apuWenhOFr+pnhJJaOVnxv07EkpR75T1EvQop5Sow/3aRhtzy/AhKwY+C2Kru1fS06dQl+37OHqsGICkX4Q+Do2nWKf5QANwocTM2Zg8j41OE1WC+Ri3hzltwhTJYULCk0Bv2jxqrd5fgTOTDthDPu+WLwAiifxzab9B117d+Ez/LTaE6kmCRZbE9uqJb1xiiW1CuJOR/TCziiCP+bBx48h47A=='
                      autoCreateTopics: false                   
                    bindings:
                      yzin:
                        consumer:
                          autoCommitOnError: true
                          startOffset: latest
                          enableDlq: true
                          dlqName: dmap_media_resend
                          configuration:
                            session.timeout.ms: 120000                             
        kafkaht:
          type: kafka
          inheritEnvironment: false
          defaultCandidate: false
          environment:
            spring:
              cloud:
                stream: 
                  kafka:
                    binder:
                      brokers: '{cipher}AQAIVNvkU9iQqhPiIsA+S/k1hXoOsVNmnh5EvP+kNiAEmPRvP80ZR7C5GFRMOkfagdhvSvtLz/Jqd/xK3QITIwoI0NBRLbTKpco6WUlMhe+ICCEjVzSQebpSZX9xqfni31s64SQGBLRWL+/aDDw7rV3XNiy8cscIzYbNcHMiSF7A7awmei1JSKtdhvbpPl3WDdL+C1RF/AhVY2B4r99pc5I5yTlmN7EXYBhASvBqN/y1jKRjKkCq2VuI1xd5wAeuybROGxEIEP/92L7yrZjglqrl658cA4WmLJkYsQ/F9PhiwbcyTAyIqGURq71ZB8WbeJVv/SUrDlN6pGRaI4zjl/QhbdhJ7FMlXulUH4f6YeN5B9Y/aLJX3SDc19Dz6T4rJb1g+zo6fAwPDE8OqI6SRf3SJwtqMxoC/1Z/5fuES7/I2HpREHarZ9ZhNbhI4N5MmTM='
                      zkNodes: '{cipher}AQCU4pggohhwuJULJ3phUsla7VIncCzqLp8jRWZ2xBylh+HUbJhEGL9B3OarCofdJUqgNhnmUbEVX4FWYwyg827MSdun6KZakByAEDjak3o500lS0qY8tm7ERvylQnilS78ICTa4XtQs7Dvol5o6J2/aalyga+u6MZ32Av9/AtemSBYidO3pquCq0X4r2JY48fanLp2PCknWvR3dESWDtpKL6vRdq36iC4HcwqbvfGbdAebFJKCWc7GdOHUnVmRztIapDnUm1lY9vD6dQhKeBKbB3hPX3spv2V80Xutt38IykQdwSoPgB5RKmDiNPn17qcaW5D1ghMsFH88EcUccYh39ASesvJ6D68L0cQ/ZhjvEgPh0pQk4/TTZySA9/AIpPZo3h5wMmcwqBtwH4WcwZest1q87HHbNq8I9JBa3dWJz2A=='
                      autoCreateTopics: false                    
                    bindings:
                      htin:
                        consumer:
                          autoCommitOnError: true
                          startOffset: latest
                          enableDlq: true
                          dlqName: dmap_media_resend
                          configuration:
                            session.timeout.ms: 120000                             
emar:
  bs:
    consumer:
      buffer:
        size: 200
        time: 1
      redis:
        key: media_mq
redis:
  connect:
    timeout: 4000
  max:
    active: 30
    idle: 10
    wait: 3000 
---
#亦庄Consumer消费杭州机房之外的kafka消息写往亦庄Redis         
spring:
  profiles: yz
  cloud:
    stream:
      bindings:
        gdin:
          destination: 5010,5011,5050,5060,5120,5140,5040,5180,5210,5220,5250,5020,5260,5270,dmap_media_resend
          binder: kafkagd
          group: yz
          contentType: text/plain
          consumer:
            headerMode: raw
            concurrency: 2
            maxAttempts: 5
        yzin:
          destination: 5010,5011,5050,5060,5120,5140,5040,5180,5210,5220,5250,5020,5260,5270,dmap_media_resend
          binder: kafkayz
          group: yz
          contentType: text/plain
          consumer:
            headerMode: raw
            concurrency: 2
            maxAttempts: 5
        htin:
          destination: 5010,5011,5050,5060,5120,5140,5040,5180,5210,5220,5250,5020,5260,5270,dmap_media_resend
          binder: kafkaht
          group: yz
          contentType: text/plain
          consumer:
            headerMode: raw
            concurrency: 2
            maxAttempts: 5
server:
  port: ${port:19930}
emar:
  bs:
    consumer:    
      redis:
        info: '{cipher}AQAJS2pp/x/kgPf+Wl1j6L6hHKBkIYXJbLwiU7d2itM7n/oWRTP9BpOll4GVQd+HiIE6/NE04wr+ujr5oRL8hJA2lZprxpOgCmfYX5D2nS3qyzBFKDpri3eRHM/N9lOt8fCrVAVMpf88JxJOKMtdmrWY1L0dLtJXKPqJc+jgND4UrR7JkS3Caic1cKPly36xi8MXIr/53Rs03FdZze7nPCQEc688CmqrdrTKx6+DgZ7a0oKd+uNZIP0pduG0Jl8ZUE7daf6MfV2CdvSKHYQ5SNx+xDSsTAqo25eMxxMouCxY2tGl8UliX9h2dHEpj31pPKoWO2s7IF8PesZYxIfn4VXjmqs6NEc1KUy4JjaLlMa6bIGt+A8TJTkRYxXMrAiG5Iievu78ngB94kwT8qI0GIsxxJnS3KvZKXaoarm/Z4UcjLUsLSvhn3ttWRksPZjUfA3SOBudzMUFSjsGII/ie9mCKyw7AQ0Qy3Xs2qTkZBWWhhLNu+IOUIxZhXIR8zC+oSHDd9eNwv5Q+wwuZ7wD+7ASl4umA2lV3Uxe06F8aeuwlKBNPjiBbcRrfx7d8Uw0f2g16EZN00D2YcfrXhopyjSmWne06ByDkpHVtT2gYPm4N7QHVhmT9pnxHlPdmiW3XhvMUF87BryX1x9PBt50iN9EY8zi9ImEgOmd7a3OUqXCRrVwVW4vxF5PQ9Pf5w765vD5jkCHGh4ceGuMa+MK5ZtR95AaMzBmX3WGIHqmgTJUU9v4CjwZVC5fPAVZa+S1UNT/t3hOmqJv+bj1cbDs9ZmbtMb8vKC0fNo0wxM9mr2Nxjc9P2QC6yFYYNkBKfeq2yRZO7hVDGivZLlaaM7n6L8/PUYTfdLQtkRBFTNNwhcsEtrUVmqB9x4VZ/3TcMFKJeOAkOJ5kVLGwluBFplz01VhMaix+0HjIEPlN/QbLmKvSzwp+DTXP8QBQTGUjk9Aipny29J4OGuWMxtL+EuLNnI6u35S0qIwiln2FOkot4DoRw=='
---
#杭州Consumer消费杭州机房之外的kafka消息写往杭州Redis         
spring:
  profiles: hz
  cloud:
    stream:
      bindings:
        gdin:
          destination: 5010,5011,5050,5060,5120,5140,5040,5180,5210,5220,5250,5020,5260,5270,dmap_media_resend
          binder: kafkagd
          group: hz
          contentType: text/plain
          consumer:
            headerMode: raw
            concurrency: 2
            maxAttempts: 5
        yzin:
          destination: 5010,5011,5050,5060,5120,5140,5040,5180,5210,5220,5250,5020,5260,5270,dmap_media_resend
          binder: kafkayz
          group: hz
          contentType: text/plain
          consumer:
            headerMode: raw
            concurrency: 2
            maxAttempts: 5
        htin:
          destination: 5010,5011,5050,5060,5120,5140,5040,5180,5210,5220,5250,5020,5260,5270,dmap_media_resend
          binder: kafkaht
          group: hz
          contentType: text/plain
          consumer:
            headerMode: raw
            concurrency: 2
            maxAttempts: 5
server:
  port: ${port:19930}
emar:
  bs:
    consumer:    
      redis:
        info: '{cipher}AQADomNV4oaIWc1VKDrIiu7joKFBQmsaEuC2Hxp3dTGfIAnqOKdqjPAbv20lbOVAMXpsGo+8rZmIYkb+ty3cl92kJPSFPDSokSItYbNaj3AF/MOxmpyOXMQQXGUjR9yW+s6WJZIDBS/r9jwg7W/VId3BJunmZR4oL/5KSJu/vwL9MRk2yTdc6Xv0lMlLCtPCaQTUBAVfh/anP9uBoR5QhtegYBJDuOwIvH2aHbtPNtPouNb7OsMVhcezBT9qbHHzLLfU8lMCY6uxAIkQw9q2iXHU97Rx1KRwE1hT/HXzmCsSFrx+wdXnNS9jbLR9DbG4aP0YginJ869iEM3XFLaaM2XUt0H6Vx/oFQyTVml0ihXlExj5EvJfoRwrHAbqRB8+DLtgg3aTgaa9JcM5aCVsvpILoyfKKwj+H5F/tIcVSf+5zM7IAsnZFjkHziCUy9QM/TbllGGOL9LRzWESNRk9GYpK+J5WE3yNaAr2wg1p/qREhK+pU6pJBISTEOkVxurGinYCIWzhBA3KcWyDNVdsWVtoAbo8/N3+xJn/nQUxFohILKBKq7fIjodkmFBCHegkYhoaLOctSmlSFNITaJXE5iU6sShJnWF0VKcZhmEzEM4VytKNnG65CtW4L3Qfhdp8whlOVrKLeBsNOpp7MVh38s64bAUvkFsFFgxirv68weM01xDZ6iuyiKlW9TyBsTZ8bnZ9X4Hog8i4DulGrRa8SZUw27esOSqIHaOs3ThMx4R8tw8w/WB362mZ9oO1vOtcb7zHi/4KH1AS7CFtkM65SnCCPXPbBglyEN1kQslE3KGVlx0KInr/mDTibhYg8HUSsUvYr+jtup2hF8MGqD7rG1aRvLOkwBAW1qva8gW3quXMeO+2Qp8Bfg4EznxtKxeyl10aAACEECCls2uiuPRfEW5cpgzF2O8lOOGQgtHIk7FaqI4qNEkxYghw7NwgAXeLErxzPhH3aFaIBaXRFy41Q8KlU8q1lNj3k7gNq1QABizP5g=='
