eureka:
  client:
    serviceUrl:
      defaultZone: '{cipher}AQA/NB/V/XGGgN5R7ArjPcgTd5E9s+8vTTXmgDM19T1z/vySVUAZ1VThdBIOJlsfOASmBd78cvJ9K+FoPIHL9r511b3BZQXbp6Q5fZZwOEriqhNzOpyPXL3dVtM3Ou6RbmtkeeXh1tL2bQhU++1p7DIPPwEUB+UpM7RGkU4aTfcO5GkGhbM/UtasOk7oS67hYXjNENQP6K262Wf3jdg1+p7madAuXru/TtOsMqoV6j0DitkD6HKXxZ7cqFwYeZgN3dQLDOUUpa/+8M8LtFTeouXVB5EwVIo6fAPXYJxRIB9RCUDxh8A0fhhSfJ23l21eZbPkw9+TK22z7COshhi0sej+23dkajFHP6++gL6RR31l3cmvjCCyt8BXaIu7JJs9p0py6RLWgWUv5fMOFK5+S5uPQ9Jt7ZHB7cFCVINp3t8G4w=='
spring:
  cloud:
    stream:
      bindings:
        gdin:
          destination: 5010,5011,5030,5050,5060,5110,5120,5140,5040,5160,5180,5190,5210,5220,5240,5250,5020,5260,5270,dmap_media_resend
          binder: kafkagd
          group: test
          contentType: text/plain
          consumer:
            headerMode: raw
            concurrency: 2
        yzin:
          destination: 5010,5011,5030,5050,5060,5110,5120,5140,5040,5160,5180,5190,5210,5220,5240,5250,5020,5260,5270,dmap_media_resend
          binder: kafkayz
          group: test
          contentType: text/plain
          consumer:
            headerMode: raw
            concurrency: 2
        htin:
          destination: 5010,5011,5030,5050,5060,5110,5120,5140,5040,5160,5180,5190,5210,5220,5240,5250,5020,5260,5270,dmap_media_resend
          binder: kafkaht
          group: test
          contentType: text/plain
          consumer:
            headerMode: raw
            concurrency: 2             
      binders:
        kafkagd:
          type: kafka
          defaultCandidate: false
          environment:
            spring:
              cloud:
                stream: 
                  kafka:
                    binder:
                      brokers: '{cipher}AQAEct4Z2gPk2i0Jvgi6kluJivEPnW2SGLRIa5FsJpPdnwplaijZChpJZTFL/1V/c8850zztaN2JwoJysGLDSxJHwoWGapHJLXaj2Yg+6T9xMf+HbyY11mVtaRge5GD+f29WbkVzuvzT1TUe5qLE3qpk8AWUQpB7LeWiBBEOEJ0e69jhc4LPpEtsryY4YIPgLV8QCyIZGh8f6q9RujrpfcHZ2ibBsfB9WuSXS9Z9ebGDCsi7fXfS8qhy67pq/k+l3cANVsDIF/j5Gukjmi43ix0WQEhU8zmQavi8zHWN0dB94fHqzIlcZC6of5s2P+BiiV6sfsT0+fRTJ7IhY9Jtc3diOVNJhlqk3e/PGZ2BTs+gh6nqGEbzX6NUoBZbt/9fjCXAsU31s4Qyeo+tLj4KBLEAbJr2+vfsdaX10tvSF19+M03pvjkRucj2mcSOdVhm/HI='
                      zkNodes: 121.201.104.50,121.201.104.52,121.201.104.53
                      requiredAcks: 1
                      autoCreateTopics: false
                    bindings:
                      gdin:
                        consumer:
                          autoRebalanceEnabled: true
                          autoCommitOffset: true
                          autoCommitOnError: false
                          startOffset: earliest
                          enableDlq: true
                          dlqName: dmap_media_resend
        kafkayz:
          type: kafka
          environment:
            spring:
              cloud:
                stream: 
                  kafka:
                    binder:
                      brokers: '{cipher}AQA+00cs6IJl8m2t2LsBYX+HWYFTiuQGW0p7Plyq6fEmvdsEBCiCx8gqGzknFQGffJN3AEL8aupgfMlgshfseUBwWtJArL/gNl9r1gfqWHe0n+sWCyI7+3+3wrogZJ01HfgRjRtxQBMCUhlGlbvytyJw3t1Sn2uAaSUOyu4MmqPsqnN+j4eYVYQYCKsqlKAk7aILafZW/GhJV3nlqlOuKh9u0VuvmHgSF6B+edzW3cZwXUl7L0ibWB/wRY+gjWz+++8M3iXOq2/nwpmStrBjtiEGKcuFYdfxvQ4h88dXIuG7eUcvnWlvBpfMg1WFIJ7HVSP8Q6Z7mU9qaU7XJ6/41wBuM160U4Gtd+L/ZftQa0VRVAy7tMKeTR4IWOMZXLhnHNRwi95tjoRJaniMntR312Hwi28m7fzzhAd4FoBsTrrwSbO5+AhIt/Ib+7Lvtlb3EPQ='
                      zkNodes: 123.59.17.83,123.59.17.180,123.59.17.181
                      requiredAcks: 1
                      autoCreateTopics: false
                    bindings:
                      yzin:
                        consumer:
                          autoRebalanceEnabled: true
                          autoCommitOffset: true
                          autoCommitOnError: false
                          startOffset: earliest
                          enableDlq: true
                          dlqName: dmap_media_resend
        kafkaht:
          type: kafka
          environment:
            spring:
              cloud:
                stream: 
                  kafka:
                    binder:
                      brokers: '{cipher}AQAIVNvkU9iQqhPiIsA+S/k1hXoOsVNmnh5EvP+kNiAEmPRvP80ZR7C5GFRMOkfagdhvSvtLz/Jqd/xK3QITIwoI0NBRLbTKpco6WUlMhe+ICCEjVzSQebpSZX9xqfni31s64SQGBLRWL+/aDDw7rV3XNiy8cscIzYbNcHMiSF7A7awmei1JSKtdhvbpPl3WDdL+C1RF/AhVY2B4r99pc5I5yTlmN7EXYBhASvBqN/y1jKRjKkCq2VuI1xd5wAeuybROGxEIEP/92L7yrZjglqrl658cA4WmLJkYsQ/F9PhiwbcyTAyIqGURq71ZB8WbeJVv/SUrDlN6pGRaI4zjl/QhbdhJ7FMlXulUH4f6YeN5B9Y/aLJX3SDc19Dz6T4rJb1g+zo6fAwPDE8OqI6SRf3SJwtqMxoC/1Z/5fuES7/I2HpREHarZ9ZhNbhI4N5MmTM='
                      zkNodes: 221.122.127.102,221.122.127.133,221.122.127.139
                      requiredAcks: 1
                      autoCreateTopics: false
                    bindings:
                      htin:
                        consumer:
                          autoRebalanceEnabled: true
                          autoCommitOffset: true
                          autoCommitOnError: false
                          startOffset: earliest
                          enableDlq: true
                          dlqName: dmap_media_resend
emar:
  bs:
    consumer:
      buffer:
        size: 800
        time: 10
      batch:
        write:
          size: 300        
      record:
        separator: @s@p
      resend:
        cron: 0 */1 * * * ?
      redis:
        key: media_mq
  log:
    format: dat                          
---
#亦庄Consumer消费杭州机房之外的消息写往亦庄Redis         
spring:
  profiles: yz
server:
  port: ${port:19930}
emar:
  log:
    directory: /data/dsp/app/consumer-stream-retry/yz
  bs:
    consumer:    
      redis:
        info: '{cipher}AQAJS2pp/x/kgPf+Wl1j6L6hHKBkIYXJbLwiU7d2itM7n/oWRTP9BpOll4GVQd+HiIE6/NE04wr+ujr5oRL8hJA2lZprxpOgCmfYX5D2nS3qyzBFKDpri3eRHM/N9lOt8fCrVAVMpf88JxJOKMtdmrWY1L0dLtJXKPqJc+jgND4UrR7JkS3Caic1cKPly36xi8MXIr/53Rs03FdZze7nPCQEc688CmqrdrTKx6+DgZ7a0oKd+uNZIP0pduG0Jl8ZUE7daf6MfV2CdvSKHYQ5SNx+xDSsTAqo25eMxxMouCxY2tGl8UliX9h2dHEpj31pPKoWO2s7IF8PesZYxIfn4VXjmqs6NEc1KUy4JjaLlMa6bIGt+A8TJTkRYxXMrAiG5Iievu78ngB94kwT8qI0GIsxxJnS3KvZKXaoarm/Z4UcjLUsLSvhn3ttWRksPZjUfA3SOBudzMUFSjsGII/ie9mCKyw7AQ0Qy3Xs2qTkZBWWhhLNu+IOUIxZhXIR8zC+oSHDd9eNwv5Q+wwuZ7wD+7ASl4umA2lV3Uxe06F8aeuwlKBNPjiBbcRrfx7d8Uw0f2g16EZN00D2YcfrXhopyjSmWne06ByDkpHVtT2gYPm4N7QHVhmT9pnxHlPdmiW3XhvMUF87BryX1x9PBt50iN9EY8zi9ImEgOmd7a3OUqXCRrVwVW4vxF5PQ9Pf5w765vD5jkCHGh4ceGuMa+MK5ZtR95AaMzBmX3WGIHqmgTJUU9v4CjwZVC5fPAVZa+S1UNT/t3hOmqJv+bj1cbDs9ZmbtMb8vKC0fNo0wxM9mr2Nxjc9P2QC6yFYYNkBKfeq2yRZO7hVDGivZLlaaM7n6L8/PUYTfdLQtkRBFTNNwhcsEtrUVmqB9x4VZ/3TcMFKJeOAkOJ5kVLGwluBFplz01VhMaix+0HjIEPlN/QbLmKvSzwp+DTXP8QBQTGUjk9Aipny29J4OGuWMxtL+EuLNnI6u35S0qIwiln2FOkot4DoRw=='
---
#亦庄Consumer消费杭州机房之外的消息写往亦庄Redis         
spring:
  profiles: yz
server:
  port: ${port:19930}
emar:
  log:
    directory: /data/dsp/app/consumer-stream-retry/hz
  bs:
    consumer:    
      redis:
        info: '{cipher}AQAJS2pp/x/kgPf+Wl1j6L6hHKBkIYXJbLwiU7d2itM7n/oWRTP9BpOll4GVQd+HiIE6/NE04wr+ujr5oRL8hJA2lZprxpOgCmfYX5D2nS3qyzBFKDpri3eRHM/N9lOt8fCrVAVMpf88JxJOKMtdmrWY1L0dLtJXKPqJc+jgND4UrR7JkS3Caic1cKPly36xi8MXIr/53Rs03FdZze7nPCQEc688CmqrdrTKx6+DgZ7a0oKd+uNZIP0pduG0Jl8ZUE7daf6MfV2CdvSKHYQ5SNx+xDSsTAqo25eMxxMouCxY2tGl8UliX9h2dHEpj31pPKoWO2s7IF8PesZYxIfn4VXjmqs6NEc1KUy4JjaLlMa6bIGt+A8TJTkRYxXMrAiG5Iievu78ngB94kwT8qI0GIsxxJnS3KvZKXaoarm/Z4UcjLUsLSvhn3ttWRksPZjUfA3SOBudzMUFSjsGII/ie9mCKyw7AQ0Qy3Xs2qTkZBWWhhLNu+IOUIxZhXIR8zC+oSHDd9eNwv5Q+wwuZ7wD+7ASl4umA2lV3Uxe06F8aeuwlKBNPjiBbcRrfx7d8Uw0f2g16EZN00D2YcfrXhopyjSmWne06ByDkpHVtT2gYPm4N7QHVhmT9pnxHlPdmiW3XhvMUF87BryX1x9PBt50iN9EY8zi9ImEgOmd7a3OUqXCRrVwVW4vxF5PQ9Pf5w765vD5jkCHGh4ceGuMa+MK5ZtR95AaMzBmX3WGIHqmgTJUU9v4CjwZVC5fPAVZa+S1UNT/t3hOmqJv+bj1cbDs9ZmbtMb8vKC0fNo0wxM9mr2Nxjc9P2QC6yFYYNkBKfeq2yRZO7hVDGivZLlaaM7n6L8/PUYTfdLQtkRBFTNNwhcsEtrUVmqB9x4VZ/3TcMFKJeOAkOJ5kVLGwluBFplz01VhMaix+0HjIEPlN/QbLmKvSzwp+DTXP8QBQTGUjk9Aipny29J4OGuWMxtL+EuLNnI6u35S0qIwiln2FOkot4DoRw=='
