spring:
  cloud:
    stream:            
      binders:
        kafkagd:
          type: kafka
          environment:
            spring:
              cloud:
                stream: 
                  kafka:
                    binder:
                      brokers: '{cipher}AQAEct4Z2gPk2i0Jvgi6kluJivEPnW2SGLRIa5FsJpPdnwplaijZChpJZTFL/1V/c8850zztaN2JwoJysGLDSxJHwoWGapHJLXaj2Yg+6T9xMf+HbyY11mVtaRge5GD+f29WbkVzuvzT1TUe5qLE3qpk8AWUQpB7LeWiBBEOEJ0e69jhc4LPpEtsryY4YIPgLV8QCyIZGh8f6q9RujrpfcHZ2ibBsfB9WuSXS9Z9ebGDCsi7fXfS8qhy67pq/k+l3cANVsDIF/j5Gukjmi43ix0WQEhU8zmQavi8zHWN0dB94fHqzIlcZC6of5s2P+BiiV6sfsT0+fRTJ7IhY9Jtc3diOVNJhlqk3e/PGZ2BTs+gh6nqGEbzX6NUoBZbt/9fjCXAsU31s4Qyeo+tLj4KBLEAbJr2+vfsdaX10tvSF19+M03pvjkRucj2mcSOdVhm/HI='
                      zkNodes: '{cipher}AQACy18dJA1HRIomSjcDx18ClYtA9fUCBXrum7FSBhPR3P16hqu+lfBZYAheOIuzdlumUSKE/LGWgnmpPb6wrHKCmZ0VtQyplPO7FLF9S5fde/mC+jMBWBE/8+a7gWHiG/bYvTu9MYnJF2xlLDi+fTGNuJdwvTmV0KRmS7Dgl0J7UmI5nj07RnMAlxp6ZerKzX/LY40YeWrcR0cjpi0j0+IgRDymuzf4B9VygsLWYNA8ZLkxLaEbqzjZu/KjrzpvBsZaEAXG7qJ6eALZUX2S81kY3cEij/EbJVlmwPi7fMvdJjCJBmc50SDK9c3l7Gjq7oHB6R6+7BgKDYtLijzooYX1eVoX7b9memJdg5tfYMPTbVO8V/rgobTeuu/uSTrKD0NK9ss6wy5YhU6l0GsvB3QWrmhxmTc00dirmV4h3SStNQ=='
                      autoCreateTopics: false
                    bindings:
                      gdin:
                        consumer:
                          autoCommitOnError: true
                          startOffset: latest
                          enableDlq: true
                          dlqName: dmap_media_resend
                          configuration:
                            session.timeout.ms: 250000                          
        kafkayz:
          type: kafka
          environment:
            spring:
              cloud:
                stream: 
                  kafka:
                    binder:
                      brokers: '{cipher}AQA+00cs6IJl8m2t2LsBYX+HWYFTiuQGW0p7Plyq6fEmvdsEBCiCx8gqGzknFQGffJN3AEL8aupgfMlgshfseUBwWtJArL/gNl9r1gfqWHe0n+sWCyI7+3+3wrogZJ01HfgRjRtxQBMCUhlGlbvytyJw3t1Sn2uAaSUOyu4MmqPsqnN+j4eYVYQYCKsqlKAk7aILafZW/GhJV3nlqlOuKh9u0VuvmHgSF6B+edzW3cZwXUl7L0ibWB/wRY+gjWz+++8M3iXOq2/nwpmStrBjtiEGKcuFYdfxvQ4h88dXIuG7eUcvnWlvBpfMg1WFIJ7HVSP8Q6Z7mU9qaU7XJ6/41wBuM160U4Gtd+L/ZftQa0VRVAy7tMKeTR4IWOMZXLhnHNRwi95tjoRJaniMntR312Hwi28m7fzzhAd4FoBsTrrwSbO5+AhIt/Ib+7Lvtlb3EPQ='
                      zkNodes: '{cipher}AQAM92XGYxBzvvPhVmloB2Xa+RYu1Z6bDIptj5dNZpgD1e5BP7I8EQS/UC0QXL93Jzy/6IyEaiOiQxruGgEOgctQHqDu9HOZLbNvJs8QTHIR5uUKirIE2RxT0pKPWszdu6ru39K4/RzpPTiBApWxQKAMRNqfh2xU6ofaqEQYN79jMYVr2usq08iaa3jmnahYrMmACGSN7tgOFEnrgAY/apuWenhOFr+pnhJJaOVnxv07EkpR75T1EvQop5Sow/3aRhtzy/AhKwY+C2Kru1fS06dQl+37OHqsGICkX4Q+Do2nWKf5QANwocTM2Zg8j41OE1WC+Ri3hzltwhTJYULCk0Bv2jxqrd5fgTOTDthDPu+WLwAiifxzab9B117d+Ez/LTaE6kmCRZbE9uqJb1xiiW1CuJOR/TCziiCP+bBx48h47A=='
                      autoCreateTopics: false                   
                    bindings:
                      yzin:
                        consumer:
                          autoCommitOnError: true
                          startOffset: latest
                          enableDlq: true
                          dlqName: dmap_media_resend
                          configuration:
                            session.timeout.ms: 250000                             
        kafkaht:
          type: kafka
          environment:
            spring:
              cloud:
                stream: 
                  kafka:
                    binder:
                      brokers: '{cipher}AQAIVNvkU9iQqhPiIsA+S/k1hXoOsVNmnh5EvP+kNiAEmPRvP80ZR7C5GFRMOkfagdhvSvtLz/Jqd/xK3QITIwoI0NBRLbTKpco6WUlMhe+ICCEjVzSQebpSZX9xqfni31s64SQGBLRWL+/aDDw7rV3XNiy8cscIzYbNcHMiSF7A7awmei1JSKtdhvbpPl3WDdL+C1RF/AhVY2B4r99pc5I5yTlmN7EXYBhASvBqN/y1jKRjKkCq2VuI1xd5wAeuybROGxEIEP/92L7yrZjglqrl658cA4WmLJkYsQ/F9PhiwbcyTAyIqGURq71ZB8WbeJVv/SUrDlN6pGRaI4zjl/QhbdhJ7FMlXulUH4f6YeN5B9Y/aLJX3SDc19Dz6T4rJb1g+zo6fAwPDE8OqI6SRf3SJwtqMxoC/1Z/5fuES7/I2HpREHarZ9ZhNbhI4N5MmTM='
                      zkNodes: '{cipher}AQCU4pggohhwuJULJ3phUsla7VIncCzqLp8jRWZ2xBylh+HUbJhEGL9B3OarCofdJUqgNhnmUbEVX4FWYwyg827MSdun6KZakByAEDjak3o500lS0qY8tm7ERvylQnilS78ICTa4XtQs7Dvol5o6J2/aalyga+u6MZ32Av9/AtemSBYidO3pquCq0X4r2JY48fanLp2PCknWvR3dESWDtpKL6vRdq36iC4HcwqbvfGbdAebFJKCWc7GdOHUnVmRztIapDnUm1lY9vD6dQhKeBKbB3hPX3spv2V80Xutt38IykQdwSoPgB5RKmDiNPn17qcaW5D1ghMsFH88EcUccYh39ASesvJ6D68L0cQ/ZhjvEgPh0pQk4/TTZySA9/AIpPZo3h5wMmcwqBtwH4WcwZest1q87HHbNq8I9JBa3dWJz2A=='
                      autoCreateTopics: false                    
                    bindings:
                      htin:
                        consumer:
                          autoCommitOnError: true
                          startOffset: latest
                          enableDlq: true
                          dlqName: dmap_media_resend
                          configuration:
                            session.timeout.ms: 250000
        kafkahz:
          type: kafka
          environment:
            spring:
              cloud:
                stream: 
                  kafka:
                    binder:
                      brokers: '{cipher}AQCF9gkyoaPwqdKriy5brcO7MOQ8BpJkotXww79FY4ccm8JhO45U5yLPaoA0A3fxTOtuux1WjPDG9ypLGLlxDlHUyXWf2XMLQqRv2MMii1tLLEojGK9HIVHfC5CZuc2BCZSWU7WLHavRXD/4EN/M2TWAwFw/J1FjU5wHGikoXpyXoJJOz+oSnDhX5CPpRkkfdW/A4xchyQX9Ysh1t3Q8XtQy8STvBfiUd9uDCqfLrEW5+9B/voZf15GRi+137VdyT6n/g8g6Z7iAInPiLZ70qLwL5VK8nWoQHGpVHfm8PQh+lMkfcXMxyt+FO+EU2EgefJwQ1sIG4ifW+MLC3bk0RdoBVMHPdxxvmvciI2lTJYBkNi4X0/3GrSGNwtmWJVGaFQ+70Pfwvf4i3PAfR0kTmnY9uSDrjuoTEqwSsM+DOjKkDaCAkFMKw3mxVAFRrPhbmFU='
                      zkNodes: '{cipher}AQBMjk299RkB3iAWjvzDxhOz0FgyyuAI/5CjwWN0sGYiqUIPBJG+IgQc63J53w9L0mPD14oL/IdHcQUeTpx0gvw87lg1ygWhle08pTFuYCWoNpgOtU5iaOAubVLSP1+iEGtpxaGRkuwexWZfC5E6+z+c/HinLv5dxSJzB24Cb9adN4nEgIjFjxhwZHy7aC1Kqd1lkLlbhWFYdNn3PvzkLZptSoS+ouK2fN25BevG7IUzEnHjwzC1UAl/ofsy6myGzHAyTOY1FDuGxpN0aBufJ3QmdFO8O62XM5CFGzQ4zu0HHZy3gBzJAFohPfPwg+P66X/aOtJFPqgfZTEEW/WqYzrhY78YZVctp+yB7WOepBBn7fpO7ymE/abJiyg6MRu4u2h+S2RE+Ex0X5m/lj9qmrfA7HEB6MkZkx2KxK7H7saE+Q=='
                      autoCreateTopics: false                    
                    bindings:
                      hzin:
                        consumer:
                          autoCommitOnError: true
                          startOffset: latest
                          enableDlq: true
                          dlqName: dmap_media_resend
                          configuration:
                            session.timeout.ms: 250000                            
emar:
  bs:
    consumer:
      buffer:
        size: 300
        time: 1
      redis:
        key: media_mq
redis:
  connect:
    timeout: 4000
  max:
    active: 30
    idle: 10
    wait: 3000 
---
#亦庄Consumer消费杭州机房之外的kafka消息写往亦庄Redis         
spring:
  profiles: yz
  cloud:
    stream:
      default:
        destination: 5010,5011,5050,5060,5120,5140,5040,5180,5210,5220,5230,5250,5020,5260,5270,5290,5310,dmap_media_resend
        group: yz
        contentType: text/plain
        consumer:
          headerMode: raw
          concurrency: 2
          maxAttempts: 1       
      bindings:
        gdin:
          binder: kafkagd
        yzin:
          binder: kafkayz
        htin:
          binder: kafkaht
        hzin:
          binder: kafkahz          
server:
  port: ${port:19930}
emar:
  bs:
    consumer:    
      redis:
        info: '{cipher}AQClYdH6eagJZB/yxucAN298K+b81CwBbPMD/2E9cAmiptyzQYQpXuSELEC7m0kZQLKa2liDQ91mwephGbskl6Ji33cyVd2+jCeo82UKsbd6EI0Q4eRcHIW4G6rzT65qxyXzeHC9VRN5iKojs86CCoVFpGy8K8BgtbnAefwjsPeWX0OAOMQFMk5Bj0Qbmkb7l87XtlHMuAGzFXihQZY3b9CwLbDh1SrudPtgnajWo7BgdxsR+W3fR1aRK2gDk0kzfZEJz0isZHtjHLtJwrDNhErtglLn3w4BSlgfni3/TzmF2lx6qzCjAkq7oWV9TEx2oLxdiVQbiGra7Pdzw3Pq9/QrY8hcuy/7zQI3uxTr2z+kdNCeaCIxSwEQk36XDx9YL2CYpmbPjFiWiYnXtUrFAum3jgX2u8Un3itMM3vDnQD1tOCD/82gBdlmTbKlLQEAbknGNtUPZdj0jK70F0yUSteg5DuUQEjiPRlJ61mmCh1e3PQqtlgrmHTvZkL4Kt4A8KTeEVe9vEK44d7SmBVGRSL5uPiQ+iSSCOPNv1qjkqf3hTpVjJ1zmAbTzLR7xAOTmjQdX2MMNpdiGGKQkzZ9d0C85xhSdl3FmZbSsh8o8XY6OZK+FxA4I6m770AgS8csxroK6Ok6t3bX0ithRyvZ2HwOv+JYsFuyPSpOj9pn8NX+LM7HtT2wLQAbPW6taTtPdZBYE81Om4G5r0usC2y4LC+JLgzYu3FOdAydQgNSOmaoaEDKSYZYectOC+UbO1RbRYTlsLLOemcJLnMVAiOrnC1Fxhz+wdk0ELTROA16O6hV7i0LIU5HwVDp0edw4bH4uWMNv2YA7rJrU121+8S+g1sSYoENahLy8ET3JsKLA3nNqZueV/Vl1OIGKijF3tLKwKHTQCqP/ByJg6BGG8LJsDcTpZxDIzlvuZUq/sAUj1OFvt4+IubcNsbL+l08y03GREz7igPXlA5B4N1ZHimJGq2oR+6lyV/dpvWVF/qmvStcwW0jb7S72gJu+y3KVx4w8T8UZNcRfBkTlFTrN3E4sVITIDiHQSbpRNr5XQ1dtQBIkQNqmx9nlklXORN+98PKJyImUBPfZYV6WSu8uMix237b'
---
#杭州Consumer消费杭州机房之外的kafka消息写往杭州Redis         
spring:
  profiles: hz
  cloud:
    stream:
      default:
        destination: 5010,5011,5050,5060,5120,5140,5040,5180,5210,5220,5230,5250,5020,5260,5270,5290,5310,dmap_media_resend
        group: hz
        contentType: text/plain
        consumer:
          headerMode: raw
          concurrency: 2
          maxAttempts: 1     
      bindings:
        gdin:
          binder: kafkagd
        yzin:
          binder: kafkayz
        htin:
          binder: kafkaht
        hzin:
          binder: kafkahz          
server:
  port: ${port:19930}
emar:
  bs:
    consumer:    
      redis:
        info: '{cipher}AQA6ZXwpOywNXIx7kvIYNfiTxzw2ZLFFMBgKZtQkxJcLk5LcVgNgMgHASlfhLHBEz7FQaUa4Fcp04jLU6jUv8kwU32x4ZzmIiNHlQ+kH7R0dsDbUwmWpA60DZZVQGvdbAjwrx36AxZgy8tYxvXL0nz2zHBrBWvzL/kRnIZkHiPo5VPcrZj480dhkWDtCj/bxKPBQUsHQ/nbYjwUdiI3ltp2KdrUYLq5sxmNs1lrMGjUmLvVGATQR8rUwJm5exwrrKznK/Xyu7dgBFxm56wFWIzEziEB9EQLoPzsG31FX4s5DeSXO7rqn3KuWJMjWAiXHjz5wH6uAkrz6ikRTarkxTJQAhPauOia2whIXBYGKLAPXN3nf8cwMaDvtLg2WMtHFFbACyQ/lvh6btfUvRH/JbyHHbLfeBBeEzBID3e1bi90bbew9gWtbukmDUpnQMoy2K3gBVZVqnEjj3dPkR5hkWt/PiWnTbppOXv8mpLwrr5XZ+0bQSBtJJHKIESukvnu9C1Z961qqOOJiy/5XOQS8jEmMWUYImh+UzUMcrs9E2RKIGbpBIC8fD4ETmAqoLAqjbbKwiSe/zodAILEU5mcFURjR2C+psGsKieyf8t3ldEhX5k0A170i5uVMJJv2UQI6VUi59ul8jUSfEzcHgjORx1vxveVKs15EXC7nL4XQ+UQNI8oGwxUtcaQyCtyNZR0+d8jAdLzvCfMA2GTr/e2+hC5zFsWiTevUCk8dw57HwTunwoLOuCYeI67Yv0TDZIh0WrD8meXPrIpgE7Yk+MscDJfPOQVEpzAQUvTNHUSPpE5hpQ8yVaSDzR+e5Z21beb3pUmLGItB/H7OF5nEZEpkYLLMW1Df/9jvGKojgGhRGBpOODt+H4gKRcwsG406rfP2W5ztf2slNOWGHOzhyLLlrv2a8tsCd1uPq2fNc5z7B8iP0DnCVyUND7TouSDqZE0ymXI14PLByH5ZKQoncrBzsrnSxVEs81ZEuyvtiXbbnsEbVRoECkDRW/u0odT7knSQkUUb/B8v1XwYf0PX1t+AFg98RR5NJRsoNfHVyWUFpV1UsB1v3i1OSrbXTffFlmwZwVHajff1VzbobF9c4ZJB/kPn'
