eureka:
  client:
    serviceUrl:
      defaultZone: '{cipher}AQAZqayNZZBQGm+6XSlpRn85ESQxVxKokpoi43nvgns8ICrAWCOX4qE1uy38rCLt4JGxTmLmoBQ062HZIWSYlL8wyw7MdWHjDNvftJusByZuWk9KbSVcCVHwO9/DPJJYKUz55NhVp4lMof6xQIvgThSf/H+AcCRVH5Mb9L6vky9i9soUPkyx3BOpH9JWHs4E2Oj9lQK5dQ1pHqOJ0TxqT122sURCDaL9kaSaTtPY7MpbKLGuDjsRXETCu3OO6s0bVBDx6AF9GVRuDD5MGTw/Q9G7QUQyh9GX0yRI5FAco+40V50tlw9Rc70bUh+6t0Pq4Tg+kknrvi7Wa97aw1a0BDMz91MowmYQs7NybKq3yLsZCvjJKf65fskMG0jGkIblojkvI4J1AU2r8kjIqKhX9kGIs/Xej+FfeUzHhq6rGaT1Uw=='
spring:
  cloud:
    stream:            
      binders:
        kafkagd:
          type: kafka
          environment:
            spring:
              cloud:
                stream: 
                  kafka:
                    binder:
                      brokers: '{cipher}AQAEct4Z2gPk2i0Jvgi6kluJivEPnW2SGLRIa5FsJpPdnwplaijZChpJZTFL/1V/c8850zztaN2JwoJysGLDSxJHwoWGapHJLXaj2Yg+6T9xMf+HbyY11mVtaRge5GD+f29WbkVzuvzT1TUe5qLE3qpk8AWUQpB7LeWiBBEOEJ0e69jhc4LPpEtsryY4YIPgLV8QCyIZGh8f6q9RujrpfcHZ2ibBsfB9WuSXS9Z9ebGDCsi7fXfS8qhy67pq/k+l3cANVsDIF/j5Gukjmi43ix0WQEhU8zmQavi8zHWN0dB94fHqzIlcZC6of5s2P+BiiV6sfsT0+fRTJ7IhY9Jtc3diOVNJhlqk3e/PGZ2BTs+gh6nqGEbzX6NUoBZbt/9fjCXAsU31s4Qyeo+tLj4KBLEAbJr2+vfsdaX10tvSF19+M03pvjkRucj2mcSOdVhm/HI='
                      zkNodes: '{cipher}AQACy18dJA1HRIomSjcDx18ClYtA9fUCBXrum7FSBhPR3P16hqu+lfBZYAheOIuzdlumUSKE/LGWgnmpPb6wrHKCmZ0VtQyplPO7FLF9S5fde/mC+jMBWBE/8+a7gWHiG/bYvTu9MYnJF2xlLDi+fTGNuJdwvTmV0KRmS7Dgl0J7UmI5nj07RnMAlxp6ZerKzX/LY40YeWrcR0cjpi0j0+IgRDymuzf4B9VygsLWYNA8ZLkxLaEbqzjZu/KjrzpvBsZaEAXG7qJ6eALZUX2S81kY3cEij/EbJVlmwPi7fMvdJjCJBmc50SDK9c3l7Gjq7oHB6R6+7BgKDYtLijzooYX1eVoX7b9memJdg5tfYMPTbVO8V/rgobTeuu/uSTrKD0NK9ss6wy5YhU6l0GsvB3QWrmhxmTc00dirmV4h3SStNQ=='
                      autoCreateTopics: false
                    bindings:
                      gdin:
                        consumer:
                          autoCommitOnError: true
                          startOffset: latest
                          enableDlq: false
                          dlqName: dmap_media_resend
                          configuration:
                            session.timeout.ms: 250000                          
        kafkayz:
          type: kafka
          environment:
            spring:
              cloud:
                stream: 
                  kafka:
                    binder:
                      brokers: '{cipher}AQA+00cs6IJl8m2t2LsBYX+HWYFTiuQGW0p7Plyq6fEmvdsEBCiCx8gqGzknFQGffJN3AEL8aupgfMlgshfseUBwWtJArL/gNl9r1gfqWHe0n+sWCyI7+3+3wrogZJ01HfgRjRtxQBMCUhlGlbvytyJw3t1Sn2uAaSUOyu4MmqPsqnN+j4eYVYQYCKsqlKAk7aILafZW/GhJV3nlqlOuKh9u0VuvmHgSF6B+edzW3cZwXUl7L0ibWB/wRY+gjWz+++8M3iXOq2/nwpmStrBjtiEGKcuFYdfxvQ4h88dXIuG7eUcvnWlvBpfMg1WFIJ7HVSP8Q6Z7mU9qaU7XJ6/41wBuM160U4Gtd+L/ZftQa0VRVAy7tMKeTR4IWOMZXLhnHNRwi95tjoRJaniMntR312Hwi28m7fzzhAd4FoBsTrrwSbO5+AhIt/Ib+7Lvtlb3EPQ='
                      zkNodes: '{cipher}AQAM92XGYxBzvvPhVmloB2Xa+RYu1Z6bDIptj5dNZpgD1e5BP7I8EQS/UC0QXL93Jzy/6IyEaiOiQxruGgEOgctQHqDu9HOZLbNvJs8QTHIR5uUKirIE2RxT0pKPWszdu6ru39K4/RzpPTiBApWxQKAMRNqfh2xU6ofaqEQYN79jMYVr2usq08iaa3jmnahYrMmACGSN7tgOFEnrgAY/apuWenhOFr+pnhJJaOVnxv07EkpR75T1EvQop5Sow/3aRhtzy/AhKwY+C2Kru1fS06dQl+37OHqsGICkX4Q+Do2nWKf5QANwocTM2Zg8j41OE1WC+Ri3hzltwhTJYULCk0Bv2jxqrd5fgTOTDthDPu+WLwAiifxzab9B117d+Ez/LTaE6kmCRZbE9uqJb1xiiW1CuJOR/TCziiCP+bBx48h47A=='
                      autoCreateTopics: false                   
                    bindings:
                      yzin:
                        consumer:
                          autoCommitOnError: true
                          startOffset: latest
                          enableDlq: false
                          dlqName: dmap_media_resend
                          configuration:
                            session.timeout.ms: 250000                             
        kafkaht:
          type: kafka
          environment:
            spring:
              cloud:
                stream: 
                  kafka:
                    binder:
                      brokers: '{cipher}AQAIVNvkU9iQqhPiIsA+S/k1hXoOsVNmnh5EvP+kNiAEmPRvP80ZR7C5GFRMOkfagdhvSvtLz/Jqd/xK3QITIwoI0NBRLbTKpco6WUlMhe+ICCEjVzSQebpSZX9xqfni31s64SQGBLRWL+/aDDw7rV3XNiy8cscIzYbNcHMiSF7A7awmei1JSKtdhvbpPl3WDdL+C1RF/AhVY2B4r99pc5I5yTlmN7EXYBhASvBqN/y1jKRjKkCq2VuI1xd5wAeuybROGxEIEP/92L7yrZjglqrl658cA4WmLJkYsQ/F9PhiwbcyTAyIqGURq71ZB8WbeJVv/SUrDlN6pGRaI4zjl/QhbdhJ7FMlXulUH4f6YeN5B9Y/aLJX3SDc19Dz6T4rJb1g+zo6fAwPDE8OqI6SRf3SJwtqMxoC/1Z/5fuES7/I2HpREHarZ9ZhNbhI4N5MmTM='
                      zkNodes: '{cipher}AQCU4pggohhwuJULJ3phUsla7VIncCzqLp8jRWZ2xBylh+HUbJhEGL9B3OarCofdJUqgNhnmUbEVX4FWYwyg827MSdun6KZakByAEDjak3o500lS0qY8tm7ERvylQnilS78ICTa4XtQs7Dvol5o6J2/aalyga+u6MZ32Av9/AtemSBYidO3pquCq0X4r2JY48fanLp2PCknWvR3dESWDtpKL6vRdq36iC4HcwqbvfGbdAebFJKCWc7GdOHUnVmRztIapDnUm1lY9vD6dQhKeBKbB3hPX3spv2V80Xutt38IykQdwSoPgB5RKmDiNPn17qcaW5D1ghMsFH88EcUccYh39ASesvJ6D68L0cQ/ZhjvEgPh0pQk4/TTZySA9/AIpPZo3h5wMmcwqBtwH4WcwZest1q87HHbNq8I9JBa3dWJz2A=='
                      autoCreateTopics: false                    
                    bindings:
                      htin:
                        consumer:
                          autoCommitOnError: true
                          startOffset: latest
                          enableDlq: false
                          dlqName: dmap_media_resend
                          configuration:
                            session.timeout.ms: 250000                             
emar:
  bs:
    consumer:
      buffer:
        size: 200
        time: 1
      redis:
        key: media_mq
redis:
  connect:
    timeout: 4000
  max:
    active: 30
    idle: 10
    wait: 3000 
---
#亦庄Consumer消费杭州机房之外的kafka消息写往亦庄Redis         
spring:
  profiles: yz
  cloud:
    stream:
      bindings:
        gdin:
          destination: 5010,5011,5050,5060,5120,5140,5040,5180,5210,5220,5250,5020,5260,5270,5290,dmap_media_resend
          binder: kafkagd
          group: yz
          contentType: text/plain
          consumer:
            headerMode: raw
            concurrency: 2
            maxAttempts: 5
        yzin:
          destination: 5010,5011,5050,5060,5120,5140,5040,5180,5210,5220,5250,5020,5260,5270,5290,dmap_media_resend
          binder: kafkayz
          group: yz
          contentType: text/plain
          consumer:
            headerMode: raw
            concurrency: 2
            maxAttempts: 5
        htin:
          destination: 5010,5011,5050,5060,5120,5140,5040,5180,5210,5220,5250,5020,5260,5270,5290,dmap_media_resend
          binder: kafkaht
          group: yz
          contentType: text/plain
          consumer:
            headerMode: raw
            concurrency: 2
            maxAttempts: 5
server:
  port: ${port:19930}
emar:
  bs:
    consumer:    
      redis:
        info: '{cipher}AQBHhM5In8FOKmppjgu1gsJc3BGcxrfYY4T1ko9jxkMN9OVt4xX6aVpTaxgfGdTDrQACEQC5N7L6I7lju3dO/Tf8+mwNdlsfHw6OeT+bayV4yRG/FGRpA8BZvrO0hjyhpYXyIXrQ1eEo1DWXQ7CAe1fK7q+dTsHJCjG3TUv0RsqMnvzAt+i6QVaXO/tQC5Ip/ALem8ZwJ0LD7ejDMvYe6yxC/8g+AnNIyYWmLyDj+j3eUhuAk2z0qTdgUlUzx0w47OQIPIkn00eTe9Qb9p5rYNe9RFuHZ+LsPMOzAFVYbsH63WMscepUkJB5ScHgIh8TRGqJ37jJMmCLXay/yVDHrhVTM6/e4+mx+0ZxMX0+btcm8KJWcYoX4xaYQKX7yv7E+4rJ2lqi+rr49qWdSjXwPrpSCdi9FPh1TfVtwfVrjT4M7sJhbQi+M9dJ5SB7ssePA6Bp4sRLfCK2s/ALbHm6qgJZIzaj9CN+cdaLhfUNuYkInb7imTJzO4ki9a0y7o/C+9Vp67NjNoe01MyvUAlSue1Dn8BouprTCk9bEw4SxeQtqfZ6SUg2jOje9hqYK+kSz8DLSfg33RKhwpv2dvpP+LH8W1LHjNRy4a3F78FMwtkXqh/npZVZftAyVrVds9pVOC9mS0UGt/NhLWWsppHCHON9EMHj/Vo61+AXxhy2gYMOk9Hd9ZjKmE1EtuVM1lVeR/xIF+AdJjqBCaHL6ne6qOjgE6VRm1rvruVTg2HemBup95BKdMdbzzvRKtk9/n4sc2/UNmUKjaYUBBLHgHClkL3B2GumCqsIQQRZC/aQgLGBKM8sUg2mu4FyKj+1vpxHtrSUy3pSlfSfnNHKk59OzIDmC/vVUHFbrGzzimrxJyAnmxJ4ZZz1ueK2MGp+RwbfL7XlnuAD8eDUmoH1fqsOmHTrrOmcAzceMQHhntVMbia1zlw4tR2g3U9FFO21QFadkeV9OeqQKa96YpTfH4wmTm3GSKcW/pNBpZoQg0VCxdZEosyNTz+TqlN3VZy+fb5V+FqVRhXuiLpkx0fhYvrI9AIm'
---
#杭州Consumer消费杭州机房之外的kafka消息写往杭州Redis         
spring:
  profiles: hz
  cloud:
    stream:
      bindings:
        gdin:
          destination: 5010,5011,5050,5060,5120,5140,5040,5180,5210,5220,5250,5020,5260,5270,5290,dmap_media_resend
          binder: kafkagd
          group: hz
          contentType: text/plain
          consumer:
            headerMode: raw
            concurrency: 2
            maxAttempts: 5
        yzin:
          destination: 5010,5011,5050,5060,5120,5140,5040,5180,5210,5220,5250,5020,5260,5270,5290,dmap_media_resend
          binder: kafkayz
          group: hz
          contentType: text/plain
          consumer:
            headerMode: raw
            concurrency: 2
            maxAttempts: 5
        htin:
          destination: 5010,5011,5050,5060,5120,5140,5040,5180,5210,5220,5250,5020,5260,5270,5290,dmap_media_resend
          binder: kafkaht
          group: hz
          contentType: text/plain
          consumer:
            headerMode: raw
            concurrency: 2
            maxAttempts: 5
server:
  port: ${port:19930}
emar:
  bs:
    consumer:    
      redis:
        info: '{cipher}AQBGIiWUSU+Y1mllUK7T5c3Oc41bjSnmlML22LGVdGqT5aOZLTge6IHaqGh98x/MoO8He96cowq5PhynJnPCs50H9AH4bw4awqpA78/jRsAfFmCCDkH35AEDSNivQlIFS+VUgjhMD4OAQFnK5sR0sHVvPuiazWcPXTjAqeWXQBgWK5bUPhZQfuj5WnrhDYNcwqYO79a2QjIuIf/iRydMu3IzvkMtQT0k8Ss3P2kDAr96nh1wTx7/ZWfLgvQViD4ItbM+AEkaBlTQCO7kzu9NFVoZt/FgQlcXcU2gTTY9Z3PFU1+yUp3KK9Rz4XTS6xVGd7bTQ0+lLVBRQDlgUYj4N5gpoyET4Kid11jXGlUvXSQTp7v69n2o+CBo6gKXdATWHK3iUglnd4/xCBlv1hps0q6oRacF7T5+9tNRDxj3d3efyxRuAGFqwQIHBpe+TE3aL/tDnYgDtKCMCP053B4Rw/62PXdDHtveCQeyfxAIv0AJ2PlBw0IYe/aqBkp3T38EYD951pSEYFNZJM/RMKo/lCwavs9WfrZK+a/0J9Z7z0BQCnrvz9jLypeAlx16G5DPyXldTrwJLk7yFTFrWu+PGJ8KKPSaCnMZEvwzFMCN7Ydbp320YHfuLRA6H8Yy8b4KTDuiwj/lQn3D8/W3rVvzhouciR6E9/viFBVfuONRqJAg+38s2+g+7v/0W7sKL2cO6GvwHzdTxM5HLm+KDQJt0fFRx88CwD2rXUA9gy8Aq4dR+/gQY6CEelSGvYaelyOpPx8ogiOgN+zFPWX2vZC3R5r5mZ/2XI03bXR1HmUtwpZskPIqE/jJ+F6Mwl789VKpdGPo6Q1vxEn9PO/ffv8dPphjEmk1hxordLT30DLH67FOqoNzvBoM3nsMhPx+/+8zbRjlayczsdubOFkW7BKop4TDHrVZiwodeorPbAZLPbUqun7l2HgpVbQ1NCv5Dt9qOYfExsYSchTXSWV5felPwhQ/34XWGh1h9/xOzmqFuViELa20jdVz7A6cVCdgGMWjqkhy6ftr7zl16lRo3F4hL95L'
