eureka:
    client:
        serviceUrl:
            defaultZone: '{cipher}AQAZqayNZZBQGm+6XSlpRn85ESQxVxKokpoi43nvgns8ICrAWCOX4qE1uy38rCLt4JGxTmLmoBQ062HZIWSYlL8wyw7MdWHjDNvftJusByZuWk9KbSVcCVHwO9/DPJJYKUz55NhVp4lMof6xQIvgThSf/H+AcCRVH5Mb9L6vky9i9soUPkyx3BOpH9JWHs4E2Oj9lQK5dQ1pHqOJ0TxqT122sURCDaL9kaSaTtPY7MpbKLGuDjsRXETCu3OO6s0bVBDx6AF9GVRuDD5MGTw/Q9G7QUQyh9GX0yRI5FAco+40V50tlw9Rc70bUh+6t0Pq4Tg+kknrvi7Wa97aw1a0BDMz91MowmYQs7NybKq3yLsZCvjJKf65fskMG0jGkIblojkvI4J1AU2r8kjIqKhX9kGIs/Xej+FfeUzHhq6rGaT1Uw=='
redis:
    cluster:
        nodes: '{cipher}AQALhFtDEJzdvsZmyE74VCIdy9NYwGI+wwuccHI52aJ4KUa5vW2kteyac3WpOP8/4IvHfoNj8hvtS20LTDchQQXVY5FXqfQ9fz2mVl7IPba74bGc7RHn1gRRvOKeWO+XfH3APwx0ileC3AK450phM7pWXNXpkI4DsqRHrN2OqwnyRRmZIJZZ6s0NOgykrE6ymmoay6uF0tmd8yFI7eQscbtxMz5UmqPUU15l9y13kUBbLLdcoiGlmdJue3sqGZ+6V+gH2FhiFNF9o+urz2hlSpbw6df38XP8066X7TEkrcMv+RDx2kAxkOhB5PgjjXFuBOTtO2VFZ1JuLsIsUua7+E0eHPVFleceBqmfKDKqGJGM1MaDqysag/3X/CLs6cNE2cn7AEkAHi2tFf+M9NEbyovPN+XUa/BsFT4yImV1Q5DyTSY7Bpj5Bf7reddJlEKNfFyUmqL3SqlFdurFumZqj7RCf91GuBq0iHOxtrEgB82aug=='
        retry:
            max:
                num: 1000
        time:
            out: 10000
    connect:
        timeout: 15000
    max:
        active: 500
        idle: 100
        wait: 10
    single:
        node:
            ip: '{cipher}AQB7kzslVrqMqMZmxZnGuXL9SoASFDIkRRJIBOuFqruisO78JaN0ev2urn3eyjbJF8H8egB+EDLRdN2CEs7oMQTI4LzkHN0d8uc4zwqi46sWwJLQkvci6hKyFaL1HjmZxDwL4FDNe9S9K75M8HRZzLu+Bs19u2AiKLSisLOYeRWIPJQA8UPeobsP0MnfI4dDLf8HuFFZ09EMbR0nzWHVtUpk3Hltyv9WqOTsZfmuGKdK2RXFXa3DW9u3S1OAjYn62y5oKlju57O7HiOXbV3kAqpU3msYgCGMVGBitquhyipQtRf+d5xyJu8rn2QrOXFbh6wfCZmSF8j2b3nVT8U4+LjU0Mtcq7YN56F3ueZqpXGmrbIlCPQsvm/D/ZH0tM+jpSs='
            port: 33334
server:
    port: 19801
spring:
    http:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        password: '{cipher}AQAoq6Vu8cBYoyJdPoK1/XV3SMeNzH6vGa/xm4Dr0BazbCmyNybliWQkEHR96HkkXjLofID/DrKPXlcf+818k2ydBDBjMXsW39ojze5vY8yQ3xskotwD7UAH3VBLWuRp5iP3fm1LnkhRqb1cNtCt2BP3KNa35rxvJxzh9kPRiN8U9U0QMS1PwYPircnNwJROgTgCYEOQbrNZPJlC5Nm1ldHHlNDaR1EkelJFlRVjL+wHIBHfWNFDJhLv5OcDAR2rIoK/BOIqQeWAgF7ojrnKsXf7ZYHJfXwldoGlAWtLR0k+D1Rx33cik14HZNXLH95hfiZOKMRHecb8jw7e+uTx9HziUkkyThutDnWB3f4dVBdaqPFYRUl8ldZIXEpRmy20ZdM='
        testWhileIdle: true
        url: '{cipher}AQCuFWBSnzNY9yMkbLABQhJgumO1ENY8m9IpGCaHRdb7+x8bXeGJ1TxIWZ/0XCcagKr51P8m/RCY6DWySWSj4U5ugGVeerA0OrvFxoCshGpaE2gxPsw63+NgbG5Sdjg6ZegrV6134D7uUKqaYynCnsbkwW3LRUs3gKzQkSo21Q0JtiO6aywKgKgGlEbkTpU9Vb7VjqaJfiuoUcn7HPpWG6nFv3byEHm4T/GOxkiZVHqyC1Zcq4znmTxcve9MeaNrqaWE805VzoLkTq2h8gkHAm/N1yzhh8VCHDpWdXjEq5f5tXJc4arKh+F+eqOuEsGeo1prKzzVysb0JC+lPPE1MaEuOTiW7nVk5SsMKmeQRStd1oOnQym1uo2bBMZefGRC085Qwd72ExxFfusShUjWjDammdoD9Qgoi2N5H3aKqznjocFrzfKD3PbRtjww6ojkWPQ='
        username: '{cipher}AQCx8LwXAgmv7ef+HThwT6SuHr5E6DpPUEPAtcfVrJOvQ0LYRXDNg9BPVVC97kjAWK+4HH1ypGl7iPivTSLLsOmkcGVf4BH17d9qkLGBtk2WKzB6rvqmKSS/HbnE9dzQXUenEQ+rIxJyzrHPZyhHONj+p3fpynNbWpwmYTJEK/Fm2DmLDp/jFV2XGQVA1eYigZxFBUQdsYwmGoe4anqf5IFPbJR7y5yaN9krP66EbkeUyTaykqDXzBbXCYeK8WpxKtAHmk9Qhzkxnvs1//n/37qyrkJNlsRbmS7SUeloJDGYq5NKhYdpNHkbXsOzaOJaErCcancOz+89sjZCxM6K1R1FmexKpQk59eLyBUgTj/4RfynU1DQjU/aYrIRBcVj5G5s='
        validationQuery: SELECT 1
    batch:
        job:
            enabled: false
    jpa:
        properties:
            hibernate:
                format_sql: true
        show-sql: true            
    hadoop:
        config:
            fs:
                defaultFS: hdfs://192.168.6.51:8020/user/tongyi/crowdpack_source
        fsshell:
            enabled: true                
emar:
    file:
        people:
            record:
                number: 1000
            directory: /dmp4/crowdpack/getDmpidNew/data/source
            file:
                size: 100
        directory: upload
    cross:
        origin: http://displayer.emarbox.com
log4j:
    logger:
        org:
            hibernate:
                type: trace
---
#qm专用数据库配置
spring:
    profiles: qm
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        password: '{cipher}AQAoq6Vu8cBYoyJdPoK1/XV3SMeNzH6vGa/xm4Dr0BazbCmyNybliWQkEHR96HkkXjLofID/DrKPXlcf+818k2ydBDBjMXsW39ojze5vY8yQ3xskotwD7UAH3VBLWuRp5iP3fm1LnkhRqb1cNtCt2BP3KNa35rxvJxzh9kPRiN8U9U0QMS1PwYPircnNwJROgTgCYEOQbrNZPJlC5Nm1ldHHlNDaR1EkelJFlRVjL+wHIBHfWNFDJhLv5OcDAR2rIoK/BOIqQeWAgF7ojrnKsXf7ZYHJfXwldoGlAWtLR0k+D1Rx33cik14HZNXLH95hfiZOKMRHecb8jw7e+uTx9HziUkkyThutDnWB3f4dVBdaqPFYRUl8ldZIXEpRmy20ZdM='
        testWhileIdle: true
        url: '{cipher}AQA6Um+z2ZtjNYov47Orn76Q+F3UIdjfwbC8NvQwumNZ/f56U2SXjKHN/0S1ugEGxUzBwN4K4DU9uDOA8FHDLtdXhFtVPw3koGAOnNbMmLqkV2sKQLUKRcqZswDza15+4qeCj1WVE5S7WUMVZU1jS4AKguY5gD16b1vsDcAaGmXXGe8uIzAHxuLJfb2gYRQCA8QTHLN59SaDbse7qJxjzhoTPg6ceKKS70W1+JK0ebS8mZTCyZJgRNPOAuralslwfmSvLC9OyriXPewJ2keh1BQ+ItwL7fHDIxfrBIquY9O84IJvP0NNoZWmPtSFMJx/KKDh3iXO4+ckKgDrYTKGXxSdD0sHzwom0im4S+g/dre4Lf+EO6rK5KtB6O2rp/+r0ohfKye24i2w6nXXchfwNnXAnf6Qx1JdHdnM4lyF5PJLdZ13FToXPQCAIyxc09HcGFg='
        username: '{cipher}AQCx8LwXAgmv7ef+HThwT6SuHr5E6DpPUEPAtcfVrJOvQ0LYRXDNg9BPVVC97kjAWK+4HH1ypGl7iPivTSLLsOmkcGVf4BH17d9qkLGBtk2WKzB6rvqmKSS/HbnE9dzQXUenEQ+rIxJyzrHPZyhHONj+p3fpynNbWpwmYTJEK/Fm2DmLDp/jFV2XGQVA1eYigZxFBUQdsYwmGoe4anqf5IFPbJR7y5yaN9krP66EbkeUyTaykqDXzBbXCYeK8WpxKtAHmk9Qhzkxnvs1//n/37qyrkJNlsRbmS7SUeloJDGYq5NKhYdpNHkbXsOzaOJaErCcancOz+89sjZCxM6K1R1FmexKpQk59eLyBUgTj/4RfynU1DQjU/aYrIRBcVj5G5s='
        validationQuery: SELECT 1  
