eureka:
  environment: production
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 4000
    wait-time-in-ms-when-sync-empty: 0
logging:
  level:
    com:
      netflix:
        discovery: 'OFF'
        eureka: 'OFF'
server:
  port: ${PORT:8761}
---
#亦庄Eureka实例
spring:
  profiles: yz
eureka:
  client:
    serviceUrl:
      defaultZone: '{cipher}AQAZRVjsmRfqsVkJ/+7Br5IJ/wDPW3qgAjMKpv6gAheJF09g5IdRzEnCCfMhRmboUIPwlPRw2bRImtRpXfjAgHQzNgBId59onz4DEEPSWaeOs52upQEj1ZlLgqgmwiyI7WCNcxDW4IZsPAbeRW6cuf5/ChIaBrHut5Xdy/FRcPMtAJ/syWDPlx/Zy1sEqnlsexN0Q0R+3mzVTScHd/H3VEGE+wVXOi/2Tnl3sJ6o6koIw1rqLfarbhvUd3prtxi71rpc4j4FmtTZ3iKO9lvQyFkY1eDNlcfOXbg2+25kz+caL1//vgZIRcQN1DcapkqZNpZTL7gwuVpRxmTFrloWpFx+fN/OYffR56E9OBa68nlY48Q0NrgkYWn/wLXuzXjYEv5LVwxV2aPxpPRTstVjznksjRt9aWFakRY8rdlwH17LaRn2YSsoDaj/LOeNYX2azdW+u3P4vJqiFfURIBuoLH9X'
---
#亦庄Eureka实例
spring:
  profiles: hz
eureka:
  client:
    serviceUrl:
      defaultZone: '{cipher}AQBQg9BIZHGKT38n4p1/ClWktFkxLs0uYWGyRGO42yZI2VlLbGMu93j40B9nhDoIe9fmoAIwULSJXI25sVGXGRbFx7xT3NzjbChVvfBR4MJR1u1w9u8pyGFuM935F57XN4E4RbLuT0Bi5jVlcEqCf3iVWQ8Wt2EHmabL++K7NTFqCy8RualMWNy+XK1rVJ2oYVObE9a0vWfHMJcs8hheLeaW5PDUqJBqhxNo/nOWZkXwumrXkKINAD9dcxYdX/r4qIdnvDivYl+Ggxr32tyPcKbNFOgKm3khnVGZ6wp6QLEL7zPzEsgOXef8fghyeOMWfnwPf9WoacYUli7Nitbyzal3CiSyKs9XwvhfVqU4dB22OzhoqWylakMTHbAotnFVXlEL1qW+dU5lP7SMB+N9/r75eXZNeeIBOs/iPd1ukXY9aQ=='      
