eureka:
  environment: production
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 4000
    wait-time-in-ms-when-sync-empty: 0
logging:
  level:
    com:
      netflix:
        discovery: 'DEBUG'
        eureka: 'DEBUG'
server:
  port: ${PORT:8761}
---
#亦庄Eureka实例
spring:
  profiles: yz
eureka:
  instance:
    hostname: '{cipher}AQB43hPrcPfUXTRby4kpQSyC+ShhIz56VfL14aQCO2YYXiDGTjq3ciq21ASpjBzgXqiCXVI18dBnFaA02kngp8e2vdIc8xUxsr61N2CACLEvu49KVD5j1Wyh3yfUF1QToSao0cflB+yZDvjZmo8tzNx/mAwvU4pZQLB7jJXMwYMglTPcgxzONLMDVwmRgRUh1/+NrQoWAPLbvKOHdQUaOCZomhHhnYOh1XyvEp0He9jSLf4boXkuetSPxicY5Q7SrF0z/rqqtq2kon35vTqlP/oVyPtqqAgdoyW0+uuk94BUcVf0GrvT71qB+Wcf5n8Vm3Wv70AaTo8ieOby4iwrs2tD/nuFFHtdxw3QHb+Po8BhR/bBr4vmtRMmyHZIxuZH02c='
    instanceId: '{cipher}AQCed36OQhmf7pkFh3KXFcQFgUFruxEm++c4R0k0O5J4I+BXxPj71YHj6PGSczyxaRC4y+w5Au1oxO0cCeOR401gR6fMNFDyc5bJNUjx/nHoky0m+hGCIef9OjZtAJAncPZVVrl7b+02TlZn/dyraiZdu/PC+pkt44BRfj5oFqJgOQt5F/bdBe0B7ULqgvFONybeLa5swoxE1g83gfH6oowC/64cmLpTMKX09DfiuNZssRvoooJ0uXcD7Fhyq6vjnmCVNTpzfJAeS08mxIOP4IQt0Dk+Zr5I7nH5MuXwWoUNgJo6etw++R9/1xjAO7OUcTxeclkckzAcGDHyIAsUaHhQk1ch8dAC9fjcjFhjySWxbR21lWV9xjl3LD1704n2QFnU8BdG2IdyB6iko+6JT0Yt'
  client:
    serviceUrl:
      defaultZone: '{cipher}AQCwzSuDM0t3CmWBzOYQ0p4d3o5QdqF3a7paukrIvYLci++nvRykqNz4Ax/61iyVIH3R7IpnRmOGdwvMbpVwVGPRqVbxPlo1E88rmyQh60OUReDbeddfJPj2lQZOsvYf7yYR5m381BLMRJ+lWrKeyg6C7iqWh2gonMqxgV9EwzO7AkjJ9A8nF/VbFkhMHvsf8xJEiGLZe8gTTeTc7Sn5Snt+x80KuzQeYOAdtqUwwnpqOQ7RXCwxW185sC/sWBeKp072dV51mjfm/LfNJDhIK50BCCo9TQOXf1t2RHT/1ufvBo2Y4Eag2yX4igk3GAerymopT4BAJ/M01Q092Du5u1ojWFwhq+pIlXnfux8VoIbSaa/1ZRNaqInN8OuYvk6y2Yp19CKdz2jIYzbtNShVe9wykDJNC6rmher465F4cWSmzw=='
---
#亦庄Eureka实例
spring:
  profiles: hz
eureka:
  instance:
    hostname: '{cipher}AQBVoi5YoxyZwdhuC1N3NOXKaH56sV3AM48Bcopfh7RrRjte4BBGWC/eNdlBvV83SAqpHn9uMXE0A595cy+pgBBrN37N5LcYuOoqcASBUeBCrsiuinMowM2H7KR9Hv0xCzmRyjhHW6OkzotzLhsmkzskRDG8dBs5PHFAQqQ6Tq6QMKnFYDiJQBeNql9jW6tUuSS0I27GxgwoNbIq3doLx8KXTvr/Qoi7L8DgrtDTVxpNG3zou0nzsoP0wNs6N1DzgE8KHwqzSCo8O7VoEbCGI+aTKRCsP6lmRUIb5az90WhFV9L6MsUp9ZW04d1RibzHU4P1He3GZGoXpfouoUX+ssXvqwVH6ravwwwBpRfmHC+L6ZtMkYUVsjvu9gBuLf46oFg='
    instanceId: '{cipher}AQAUESNTLQMsGp1LUOrau+KcWqFl4Ljo83DUahWugfzLaBYuY4SMp3cn/yVAMmnxlVS4uhxQkaO5GPAoYpzUpi5yfvOVfhmoUCpcnBWPGKWvhryIzN0E3nLr4cxliDVRW2pEYXxufulYzMxkqSeqeqot9q7AGJgwzCWyPqFUs++TeWsq9LAgeeBUU18EaH/xalPk1hj02ErmxqyHguXVViJX69ogM0EB734+Zo/bLl+kNng4U/N+hj0Fj6l+jsDyipC6cXBj2tLgYd3O4tFNGDhBNJYl9MC6ksgiTNmiyniSBtwBPWm0dmQzCrRpLXVEGDoBWqzVuFGa1z+6wdKQNUUagBE/FsguVocZbKM7PXPMm4dGIQ6Yco1HmsMd1ceAt/4JKWYsLnPZPV2PHif0soLhYtWzyVKsQyuOwQKyM4fbuw=='
  client:
    serviceUrl:
      defaultZone: '{cipher}AQBQg9BIZHGKT38n4p1/ClWktFkxLs0uYWGyRGO42yZI2VlLbGMu93j40B9nhDoIe9fmoAIwULSJXI25sVGXGRbFx7xT3NzjbChVvfBR4MJR1u1w9u8pyGFuM935F57XN4E4RbLuT0Bi5jVlcEqCf3iVWQ8Wt2EHmabL++K7NTFqCy8RualMWNy+XK1rVJ2oYVObE9a0vWfHMJcs8hheLeaW5PDUqJBqhxNo/nOWZkXwumrXkKINAD9dcxYdX/r4qIdnvDivYl+Ggxr32tyPcKbNFOgKm3khnVGZ6wp6QLEL7zPzEsgOXef8fghyeOMWfnwPf9WoacYUli7Nitbyzal3CiSyKs9XwvhfVqU4dB22OzhoqWylakMTHbAotnFVXlEL1qW+dU5lP7SMB+N9/r75eXZNeeIBOs/iPd1ukXY9aQ=='      
