eureka:
  environment: production
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 4000
    wait-time-in-ms-when-sync-empty: 0
logging:
  level:
    com:
      netflix:
        discovery: 'OFF'
        eureka: 'OFF'
server:
  port: ${PORT:8761}
---
#亦庄Eureka实例
spring:
  profiles: yz
eureka:
  instance:
    hostname: '{cipher}AQCH4FcYMl+hum9jNptnXkgfyn4F98AGCGi50jEBC4k6AzZNUeqyReuV4FPiDI9TPdq+qbtWbiAzYZ0YAz3Zn6T46FTjRuOyUYKncQLinyBcvlLcRZlNdyeEla9Se1Au++oO1nrrAvU5eXfrSBXwVKz4B6asrmNNuAMODGc/LCF4bZ01viefFYd0KRGdv4uOCpIayFiWOo2ue4XpmuUjJFY/fz+xOQcS0Sq3HE3QXbyWqlvHNcctIMgBMpnYiwW9saCiEyjyftH+Sy4QqNiBXvzLWlXqYi82vjL7nUZNfig62BQ9U/GVt7wriv7MoEWFAWqOK+WbIUENPNBvH0it9wOyDYURvUbkDR6Djbs1O6PoGAhM7/+jlX5FVVr8u5oV+1w='
  client:
    serviceUrl:
      defaultZone: '{cipher}AQCwzSuDM0t3CmWBzOYQ0p4d3o5QdqF3a7paukrIvYLci++nvRykqNz4Ax/61iyVIH3R7IpnRmOGdwvMbpVwVGPRqVbxPlo1E88rmyQh60OUReDbeddfJPj2lQZOsvYf7yYR5m381BLMRJ+lWrKeyg6C7iqWh2gonMqxgV9EwzO7AkjJ9A8nF/VbFkhMHvsf8xJEiGLZe8gTTeTc7Sn5Snt+x80KuzQeYOAdtqUwwnpqOQ7RXCwxW185sC/sWBeKp072dV51mjfm/LfNJDhIK50BCCo9TQOXf1t2RHT/1ufvBo2Y4Eag2yX4igk3GAerymopT4BAJ/M01Q092Du5u1ojWFwhq+pIlXnfux8VoIbSaa/1ZRNaqInN8OuYvk6y2Yp19CKdz2jIYzbtNShVe9wykDJNC6rmher465F4cWSmzw=='
---
#亦庄Eureka实例
spring:
  profiles: hz
eureka:
  instance:
    hostname: '{cipher}AQAgpL0u/Om3FxKbizZ+5i5TuIEzVS1H0n8y7De61gSUf1/K0WQpaaCeHy8YAO93DQTyMHNBPkAUgU9hd/qM/GP6R5pkJJ03YLMWjqzawr01Tlkt0QnJb8O6Zjsslb7l49ok7eMyw67GY4Ga9Cd4iRWcvNN0RXY6H16q62SUG0tEB8Lits8II3lZUm7bb5JCjjHk0EJlh4KAkAUfVKUW1Dnu7AgMMPxRm5YOHroWSITsjIZCUYOdl3YC5LnK6x5tv62SC7Gy+wiozPCK61nyNcDUN6cuhK9KgEpOVvwMaxKocY6ri0/7aAaCJBnpLle60SgsCyrJo6gMeCx/9FjvEvkf9n1oThUNJe7iziyOVQYM6PTZrVp9OS+lSRUVvKQXhL8='
  client:
    serviceUrl:
      defaultZone: '{cipher}AQBQg9BIZHGKT38n4p1/ClWktFkxLs0uYWGyRGO42yZI2VlLbGMu93j40B9nhDoIe9fmoAIwULSJXI25sVGXGRbFx7xT3NzjbChVvfBR4MJR1u1w9u8pyGFuM935F57XN4E4RbLuT0Bi5jVlcEqCf3iVWQ8Wt2EHmabL++K7NTFqCy8RualMWNy+XK1rVJ2oYVObE9a0vWfHMJcs8hheLeaW5PDUqJBqhxNo/nOWZkXwumrXkKINAD9dcxYdX/r4qIdnvDivYl+Ggxr32tyPcKbNFOgKm3khnVGZ6wp6QLEL7zPzEsgOXef8fghyeOMWfnwPf9WoacYUli7Nitbyzal3CiSyKs9XwvhfVqU4dB22OzhoqWylakMTHbAotnFVXlEL1qW+dU5lP7SMB+N9/r75eXZNeeIBOs/iPd1ukXY9aQ=='      
