eureka:
  environment: production
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    prefer-ip-address: false
  client:
    fetch-registry: false
    register-with-eureka: true
  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 4000
    wait-time-in-ms-when-sync-empty: 0
logging:
  level:
    com:
      netflix:
        discovery: 'OFF'
        eureka: 'OFF'
server:
  port: ${PORT:8761}
---
#亦庄Eureka实例
spring:
  profiles: yz
eureka:
  instance:
    hostname: 115.231.106.46
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
---
#亦庄Eureka实例
spring:
  profiles: hz
eureka:
  instance:
    hostname: 123.59.17.84
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/      
