
eureka:
    client:
        serviceUrl:
            defaultZone: '{cipher}AQA/NB/V/XGGgN5R7ArjPcgTd5E9s+8vTTXmgDM19T1z/vySVUAZ1VThdBIOJlsfOASmBd78cvJ9K+FoPIHL9r511b3BZQXbp6Q5fZZwOEriqhNzOpyPXL3dVtM3Ou6RbmtkeeXh1tL2bQhU++1p7DIPPwEUB+UpM7RGkU4aTfcO5GkGhbM/UtasOk7oS67hYXjNENQP6K262Wf3jdg1+p7madAuXru/TtOsMqoV6j0DitkD6HKXxZ7cqFwYeZgN3dQLDOUUpa/+8M8LtFTeouXVB5EwVIo6fAPXYJxRIB9RCUDxh8A0fhhSfJ23l21eZbPkw9+TK22z7COshhi0sej+23dkajFHP6++gL6RR31l3cmvjCCyt8BXaIu7JJs9p0py6RLWgWUv5fMOFK5+S5uPQ9Jt7ZHB7cFCVINp3t8G4w=='
server:
    port: 19806
spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        password: '{cipher}AQAoq6Vu8cBYoyJdPoK1/XV3SMeNzH6vGa/xm4Dr0BazbCmyNybliWQkEHR96HkkXjLofID/DrKPXlcf+818k2ydBDBjMXsW39ojze5vY8yQ3xskotwD7UAH3VBLWuRp5iP3fm1LnkhRqb1cNtCt2BP3KNa35rxvJxzh9kPRiN8U9U0QMS1PwYPircnNwJROgTgCYEOQbrNZPJlC5Nm1ldHHlNDaR1EkelJFlRVjL+wHIBHfWNFDJhLv5OcDAR2rIoK/BOIqQeWAgF7ojrnKsXf7ZYHJfXwldoGlAWtLR0k+D1Rx33cik14HZNXLH95hfiZOKMRHecb8jw7e+uTx9HziUkkyThutDnWB3f4dVBdaqPFYRUl8ldZIXEpRmy20ZdM='
        testWhileIdle: true
        url: '{cipher}AQCuFWBSnzNY9yMkbLABQhJgumO1ENY8m9IpGCaHRdb7+x8bXeGJ1TxIWZ/0XCcagKr51P8m/RCY6DWySWSj4U5ugGVeerA0OrvFxoCshGpaE2gxPsw63+NgbG5Sdjg6ZegrV6134D7uUKqaYynCnsbkwW3LRUs3gKzQkSo21Q0JtiO6aywKgKgGlEbkTpU9Vb7VjqaJfiuoUcn7HPpWG6nFv3byEHm4T/GOxkiZVHqyC1Zcq4znmTxcve9MeaNrqaWE805VzoLkTq2h8gkHAm/N1yzhh8VCHDpWdXjEq5f5tXJc4arKh+F+eqOuEsGeo1prKzzVysb0JC+lPPE1MaEuOTiW7nVk5SsMKmeQRStd1oOnQym1uo2bBMZefGRC085Qwd72ExxFfusShUjWjDammdoD9Qgoi2N5H3aKqznjocFrzfKD3PbRtjww6ojkWPQ='
        username: '{cipher}AQCx8LwXAgmv7ef+HThwT6SuHr5E6DpPUEPAtcfVrJOvQ0LYRXDNg9BPVVC97kjAWK+4HH1ypGl7iPivTSLLsOmkcGVf4BH17d9qkLGBtk2WKzB6rvqmKSS/HbnE9dzQXUenEQ+rIxJyzrHPZyhHONj+p3fpynNbWpwmYTJEK/Fm2DmLDp/jFV2XGQVA1eYigZxFBUQdsYwmGoe4anqf5IFPbJR7y5yaN9krP66EbkeUyTaykqDXzBbXCYeK8WpxKtAHmk9Qhzkxnvs1//n/37qyrkJNlsRbmS7SUeloJDGYq5NKhYdpNHkbXsOzaOJaErCcancOz+89sjZCxM6K1R1FmexKpQk59eLyBUgTj/4RfynU1DQjU/aYrIRBcVj5G5s='
        validationQuery: SELECT 1
    redis:
        cluster:
            max-redirects: 100
            yz:
                nodes: 123.59.18.131:12340,123.59.18.206:12342
        pool:
            max-active: -1
            max-idle: 8
            max-wait: -1
            min-idle: 0                    
    jpa:
        properties:
            hibernate:
                format_sql: true
        show-sql: true                
