logging:
  level:
    com:
      emarbox: INFO
    org:
      springframework:
        web: INFO 
---
#广东统计程序
spring:
  profiles: gd
  cloud:
    stream:
      bindings:
        input:
          group: statics
          destination: report_imp_pc_v1,report_cli_pc_v1,report_cli_v1,report_imp_v1
        output:
          destination: statics
      kafka:
        binder:
          brokers: 121.201.104.50:9092,121.201.104.52:9092,121.201.104.53:9092
          zkNodes: 121.201.104.50:2181,121.201.104.52:2181,121.201.104.53:2181
server:
  port: ${port:19940}
                    
