logging:
  level:
    com:
      emarbox: INFO
    org:
      springframework:
        web: INFO 
---
#广东统计程序
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: '{cipher}AQAoq6Vu8cBYoyJdPoK1/XV3SMeNzH6vGa/xm4Dr0BazbCmyNybliWQkEHR96HkkXjLofID/DrKPXlcf+818k2ydBDBjMXsW39ojze5vY8yQ3xskotwD7UAH3VBLWuRp5iP3fm1LnkhRqb1cNtCt2BP3KNa35rxvJxzh9kPRiN8U9U0QMS1PwYPircnNwJROgTgCYEOQbrNZPJlC5Nm1ldHHlNDaR1EkelJFlRVjL+wHIBHfWNFDJhLv5OcDAR2rIoK/BOIqQeWAgF7ojrnKsXf7ZYHJfXwldoGlAWtLR0k+D1Rx33cik14HZNXLH95hfiZOKMRHecb8jw7e+uTx9HziUkkyThutDnWB3f4dVBdaqPFYRUl8ldZIXEpRmy20ZdM='
    testWhileIdle: true
    url: '{cipher}AQCuFWBSnzNY9yMkbLABQhJgumO1ENY8m9IpGCaHRdb7+x8bXeGJ1TxIWZ/0XCcagKr51P8m/RCY6DWySWSj4U5ugGVeerA0OrvFxoCshGpaE2gxPsw63+NgbG5Sdjg6ZegrV6134D7uUKqaYynCnsbkwW3LRUs3gKzQkSo21Q0JtiO6aywKgKgGlEbkTpU9Vb7VjqaJfiuoUcn7HPpWG6nFv3byEHm4T/GOxkiZVHqyC1Zcq4znmTxcve9MeaNrqaWE805VzoLkTq2h8gkHAm/N1yzhh8VCHDpWdXjEq5f5tXJc4arKh+F+eqOuEsGeo1prKzzVysb0JC+lPPE1MaEuOTiW7nVk5SsMKmeQRStd1oOnQym1uo2bBMZefGRC085Qwd72ExxFfusShUjWjDammdoD9Qgoi2N5H3aKqznjocFrzfKD3PbRtjww6ojkWPQ='
    username: '{cipher}AQCx8LwXAgmv7ef+HThwT6SuHr5E6DpPUEPAtcfVrJOvQ0LYRXDNg9BPVVC97kjAWK+4HH1ypGl7iPivTSLLsOmkcGVf4BH17d9qkLGBtk2WKzB6rvqmKSS/HbnE9dzQXUenEQ+rIxJyzrHPZyhHONj+p3fpynNbWpwmYTJEK/Fm2DmLDp/jFV2XGQVA1eYigZxFBUQdsYwmGoe4anqf5IFPbJR7y5yaN9krP66EbkeUyTaykqDXzBbXCYeK8WpxKtAHmk9Qhzkxnvs1//n/37qyrkJNlsRbmS7SUeloJDGYq5NKhYdpNHkbXsOzaOJaErCcancOz+89sjZCxM6K1R1FmexKpQk59eLyBUgTj/4RfynU1DQjU/aYrIRBcVj5G5s='
    validationQuery: SELECT 1  
  profiles: gd
  cloud:
    stream:
      bindings:
        input:
          consumer:
            headerMode: raw
          group: statics
          destination: report_imp_pc_v1,report_cli_pc_v1,report_cli_v1,report_imp_v1
          contentType: text/plain
        output:
          destination: statics
          producer:
            value:
              serializer: org.apache.kafka.common.serialization.StringSerializer
            key:
              serializer: org.apache.kafka.common.serialization.StringSerializer
          useNativeEncoding: true
      kafka:
        binder:
          brokers: 121.201.104.50:9092,121.201.104.52:9092,121.201.104.53:9092
          zkNodes: 121.201.104.50:2181,121.201.104.52:2181,121.201.104.53:2181        
server:
  port: ${port:19940}
                    
