
eureka:
    client:
        serviceUrl:
            defaultZone: '{cipher}AQA/NB/V/XGGgN5R7ArjPcgTd5E9s+8vTTXmgDM19T1z/vySVUAZ1VThdBIOJlsfOASmBd78cvJ9K+FoPIHL9r511b3BZQXbp6Q5fZZwOEriqhNzOpyPXL3dVtM3Ou6RbmtkeeXh1tL2bQhU++1p7DIPPwEUB+UpM7RGkU4aTfcO5GkGhbM/UtasOk7oS67hYXjNENQP6K262Wf3jdg1+p7madAuXru/TtOsMqoV6j0DitkD6HKXxZ7cqFwYeZgN3dQLDOUUpa/+8M8LtFTeouXVB5EwVIo6fAPXYJxRIB9RCUDxh8A0fhhSfJ23l21eZbPkw9+TK22z7COshhi0sej+23dkajFHP6++gL6RR31l3cmvjCCyt8BXaIu7JJs9p0py6RLWgWUv5fMOFK5+S5uPQ9Jt7ZHB7cFCVINp3t8G4w=='
server:
    port: 19806
spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        password: '{cipher}AQA58d6l0FZfF2MTP7O9aj/ZJR0YooQTc2CM+O69RzZH8hn533Gsg1P2nSoRYXokxsm8Y0mm0o720ycl2SHRby0vKS0BKbZ/kEen4b8m0SOgkHVFRaK1KOjGu/DPjaVb/6Rz0REUYzFB5JVVH54+8Psfxf1cGsMfW7Y6GvIyRt/OKYra3pcBS/t/mF26SrZUnZOmbV8nuZqYTH3ou0oqrlYAvPNl5bDObEQdpi44QJMqurrD1//fwyFvnxA/o3tznw7Rd54Ei7Ht9e9/4ioRg7PUDsHVcVayeo+PzLZPAUEgD7T+WfN0pQAamiDM4Dov9xRg5mwC11YDUfkDZGGlwv0IlDJV4PJJcheraPha5Kwn2mWlM2Sheiq6pf70JAFn90dpg+o4hiMC37KwCPnyjKgZx+PYS5G+p+XBLSqz5VmEDYhI/QfvoNkU/jjy3li3Bxg='
        testWhileIdle: true
        url: '{cipher}AQCuFWBSnzNY9yMkbLABQhJgumO1ENY8m9IpGCaHRdb7+x8bXeGJ1TxIWZ/0XCcagKr51P8m/RCY6DWySWSj4U5ugGVeerA0OrvFxoCshGpaE2gxPsw63+NgbG5Sdjg6ZegrV6134D7uUKqaYynCnsbkwW3LRUs3gKzQkSo21Q0JtiO6aywKgKgGlEbkTpU9Vb7VjqaJfiuoUcn7HPpWG6nFv3byEHm4T/GOxkiZVHqyC1Zcq4znmTxcve9MeaNrqaWE805VzoLkTq2h8gkHAm/N1yzhh8VCHDpWdXjEq5f5tXJc4arKh+F+eqOuEsGeo1prKzzVysb0JC+lPPE1MaEuOTiW7nVk5SsMKmeQRStd1oOnQym1uo2bBMZefGRC085Qwd72ExxFfusShUjWjDammdoD9Qgoi2N5H3aKqznjocFrzfKD3PbRtjww6ojkWPQ='
        username: '{cipher}AQCx8LwXAgmv7ef+HThwT6SuHr5E6DpPUEPAtcfVrJOvQ0LYRXDNg9BPVVC97kjAWK+4HH1ypGl7iPivTSLLsOmkcGVf4BH17d9qkLGBtk2WKzB6rvqmKSS/HbnE9dzQXUenEQ+rIxJyzrHPZyhHONj+p3fpynNbWpwmYTJEK/Fm2DmLDp/jFV2XGQVA1eYigZxFBUQdsYwmGoe4anqf5IFPbJR7y5yaN9krP66EbkeUyTaykqDXzBbXCYeK8WpxKtAHmk9Qhzkxnvs1//n/37qyrkJNlsRbmS7SUeloJDGYq5NKhYdpNHkbXsOzaOJaErCcancOz+89sjZCxM6K1R1FmexKpQk59eLyBUgTj/4RfynU1DQjU/aYrIRBcVj5G5s='
        validationQuery: SELECT 1
spring:
    redis:
        cluster:
            max-redirects: 100
            yz:
                nodes: 
                    - 192.168.7.131:12770
                    - 192.168.7.206:12770
            sh:
                nodes:
---
#qm专用数据库配置
spring:
    profiles: qm
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        password: '{cipher}AQAoq6Vu8cBYoyJdPoK1/XV3SMeNzH6vGa/xm4Dr0BazbCmyNybliWQkEHR96HkkXjLofID/DrKPXlcf+818k2ydBDBjMXsW39ojze5vY8yQ3xskotwD7UAH3VBLWuRp5iP3fm1LnkhRqb1cNtCt2BP3KNa35rxvJxzh9kPRiN8U9U0QMS1PwYPircnNwJROgTgCYEOQbrNZPJlC5Nm1ldHHlNDaR1EkelJFlRVjL+wHIBHfWNFDJhLv5OcDAR2rIoK/BOIqQeWAgF7ojrnKsXf7ZYHJfXwldoGlAWtLR0k+D1Rx33cik14HZNXLH95hfiZOKMRHecb8jw7e+uTx9HziUkkyThutDnWB3f4dVBdaqPFYRUl8ldZIXEpRmy20ZdM='
        testWhileIdle: true
        url: '{cipher}AQA6Um+z2ZtjNYov47Orn76Q+F3UIdjfwbC8NvQwumNZ/f56U2SXjKHN/0S1ugEGxUzBwN4K4DU9uDOA8FHDLtdXhFtVPw3koGAOnNbMmLqkV2sKQLUKRcqZswDza15+4qeCj1WVE5S7WUMVZU1jS4AKguY5gD16b1vsDcAaGmXXGe8uIzAHxuLJfb2gYRQCA8QTHLN59SaDbse7qJxjzhoTPg6ceKKS70W1+JK0ebS8mZTCyZJgRNPOAuralslwfmSvLC9OyriXPewJ2keh1BQ+ItwL7fHDIxfrBIquY9O84IJvP0NNoZWmPtSFMJx/KKDh3iXO4+ckKgDrYTKGXxSdD0sHzwom0im4S+g/dre4Lf+EO6rK5KtB6O2rp/+r0ohfKye24i2w6nXXchfwNnXAnf6Qx1JdHdnM4lyF5PJLdZ13FToXPQCAIyxc09HcGFg='
        username: '{cipher}AQCx8LwXAgmv7ef+HThwT6SuHr5E6DpPUEPAtcfVrJOvQ0LYRXDNg9BPVVC97kjAWK+4HH1ypGl7iPivTSLLsOmkcGVf4BH17d9qkLGBtk2WKzB6rvqmKSS/HbnE9dzQXUenEQ+rIxJyzrHPZyhHONj+p3fpynNbWpwmYTJEK/Fm2DmLDp/jFV2XGQVA1eYigZxFBUQdsYwmGoe4anqf5IFPbJR7y5yaN9krP66EbkeUyTaykqDXzBbXCYeK8WpxKtAHmk9Qhzkxnvs1//n/37qyrkJNlsRbmS7SUeloJDGYq5NKhYdpNHkbXsOzaOJaErCcancOz+89sjZCxM6K1R1FmexKpQk59eLyBUgTj/4RfynU1DQjU/aYrIRBcVj5G5s='
        validationQuery: SELECT 1  
